/*
 * generated by Xtext 2.25.0
 */
package rest.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import rest.ide.contentassist.antlr.internal.InternalRestParser;
import rest.services.RestGrammarAccess;

public class RestParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(RestGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, RestGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRequestAccess().getAlternatives(), "rule__Request__Alternatives");
			builder.put(grammarAccess.getOperationAccess().getAlternatives(), "rule__Operation__Alternatives");
			builder.put(grammarAccess.getDataAccess().getAlternatives(), "rule__Data__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getRestSystemAccess().getGroup(), "rule__RestSystem__Group__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_3(), "rule__RestSystem__Group_3__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_3_3(), "rule__RestSystem__Group_3_3__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_4(), "rule__RestSystem__Group_4__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_4_3(), "rule__RestSystem__Group_4_3__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_5(), "rule__RestSystem__Group_5__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_5_3(), "rule__RestSystem__Group_5_3__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_6(), "rule__RestSystem__Group_6__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_6_3(), "rule__RestSystem__Group_6_3__0");
			builder.put(grammarAccess.getStructAccess().getGroup(), "rule__Struct__Group__0");
			builder.put(grammarAccess.getStructAccess().getGroup_3(), "rule__Struct__Group_3__0");
			builder.put(grammarAccess.getAnswerAccess().getGroup(), "rule__Answer__Group__0");
			builder.put(grammarAccess.getAnswerAccess().getGroup_3(), "rule__Answer__Group_3__0");
			builder.put(grammarAccess.getAnswerAccess().getGroup_4(), "rule__Answer__Group_4__0");
			builder.put(grammarAccess.getRouteAccess().getGroup(), "rule__Route__Group__0");
			builder.put(grammarAccess.getRouteAccess().getGroup_5(), "rule__Route__Group_5__0");
			builder.put(grammarAccess.getReGetAccess().getGroup(), "rule__ReGet__Group__0");
			builder.put(grammarAccess.getReGetAccess().getGroup_2(), "rule__ReGet__Group_2__0");
			builder.put(grammarAccess.getReGetAccess().getGroup_2_3(), "rule__ReGet__Group_2_3__0");
			builder.put(grammarAccess.getReGetAccess().getGroup_7(), "rule__ReGet__Group_7__0");
			builder.put(grammarAccess.getReGetAccess().getGroup_7_3(), "rule__ReGet__Group_7_3__0");
			builder.put(grammarAccess.getRePostAccess().getGroup(), "rule__RePost__Group__0");
			builder.put(grammarAccess.getRePostAccess().getGroup_2(), "rule__RePost__Group_2__0");
			builder.put(grammarAccess.getRePostAccess().getGroup_2_3(), "rule__RePost__Group_2_3__0");
			builder.put(grammarAccess.getRePostAccess().getGroup_7(), "rule__RePost__Group_7__0");
			builder.put(grammarAccess.getRePostAccess().getGroup_7_3(), "rule__RePost__Group_7_3__0");
			builder.put(grammarAccess.getRePutAccess().getGroup(), "rule__RePut__Group__0");
			builder.put(grammarAccess.getRePutAccess().getGroup_2(), "rule__RePut__Group_2__0");
			builder.put(grammarAccess.getRePutAccess().getGroup_2_3(), "rule__RePut__Group_2_3__0");
			builder.put(grammarAccess.getRePutAccess().getGroup_7(), "rule__RePut__Group_7__0");
			builder.put(grammarAccess.getRePutAccess().getGroup_7_3(), "rule__RePut__Group_7_3__0");
			builder.put(grammarAccess.getReDeleteAccess().getGroup(), "rule__ReDelete__Group__0");
			builder.put(grammarAccess.getReDeleteAccess().getGroup_2(), "rule__ReDelete__Group_2__0");
			builder.put(grammarAccess.getReDeleteAccess().getGroup_2_3(), "rule__ReDelete__Group_2_3__0");
			builder.put(grammarAccess.getReDeleteAccess().getGroup_7(), "rule__ReDelete__Group_7__0");
			builder.put(grammarAccess.getReDeleteAccess().getGroup_7_3(), "rule__ReDelete__Group_7_3__0");
			builder.put(grammarAccess.getSegmentAccess().getGroup(), "rule__Segment__Group__0");
			builder.put(grammarAccess.getSegmentAccess().getGroup_3(), "rule__Segment__Group_3__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getAttachmentsAccess().getGroup(), "rule__Attachments__Group__0");
			builder.put(grammarAccess.getRandomAccess().getGroup(), "rule__Random__Group__0");
			builder.put(grammarAccess.getOpCreateAccess().getGroup(), "rule__OpCreate__Group__0");
			builder.put(grammarAccess.getOpCreateAccess().getGroup_2(), "rule__OpCreate__Group_2__0");
			builder.put(grammarAccess.getOpCreateAccess().getGroup_7(), "rule__OpCreate__Group_7__0");
			builder.put(grammarAccess.getOpCreateAccess().getGroup_7_3(), "rule__OpCreate__Group_7_3__0");
			builder.put(grammarAccess.getOpReadAccess().getGroup(), "rule__OpRead__Group__0");
			builder.put(grammarAccess.getOpReadAccess().getGroup_2(), "rule__OpRead__Group_2__0");
			builder.put(grammarAccess.getOpReadAccess().getGroup_7(), "rule__OpRead__Group_7__0");
			builder.put(grammarAccess.getOpReadAccess().getGroup_7_3(), "rule__OpRead__Group_7_3__0");
			builder.put(grammarAccess.getOpUpdateAccess().getGroup(), "rule__OpUpdate__Group__0");
			builder.put(grammarAccess.getOpUpdateAccess().getGroup_2(), "rule__OpUpdate__Group_2__0");
			builder.put(grammarAccess.getOpUpdateAccess().getGroup_7(), "rule__OpUpdate__Group_7__0");
			builder.put(grammarAccess.getOpUpdateAccess().getGroup_7_3(), "rule__OpUpdate__Group_7_3__0");
			builder.put(grammarAccess.getOpDeleteAccess().getGroup(), "rule__OpDelete__Group__0");
			builder.put(grammarAccess.getOpDeleteAccess().getGroup_2(), "rule__OpDelete__Group_2__0");
			builder.put(grammarAccess.getFieldSetAccess().getGroup(), "rule__FieldSet__Group__0");
			builder.put(grammarAccess.getFieldSetAccess().getGroup_4(), "rule__FieldSet__Group_4__0");
			builder.put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getRestSystemAccess().getRequestAssignment_3_2(), "rule__RestSystem__RequestAssignment_3_2");
			builder.put(grammarAccess.getRestSystemAccess().getRequestAssignment_3_3_1(), "rule__RestSystem__RequestAssignment_3_3_1");
			builder.put(grammarAccess.getRestSystemAccess().getStructAssignment_4_2(), "rule__RestSystem__StructAssignment_4_2");
			builder.put(grammarAccess.getRestSystemAccess().getStructAssignment_4_3_1(), "rule__RestSystem__StructAssignment_4_3_1");
			builder.put(grammarAccess.getRestSystemAccess().getOperationAssignment_5_2(), "rule__RestSystem__OperationAssignment_5_2");
			builder.put(grammarAccess.getRestSystemAccess().getOperationAssignment_5_3_1(), "rule__RestSystem__OperationAssignment_5_3_1");
			builder.put(grammarAccess.getRestSystemAccess().getAnswerAssignment_6_2(), "rule__RestSystem__AnswerAssignment_6_2");
			builder.put(grammarAccess.getRestSystemAccess().getAnswerAssignment_6_3_1(), "rule__RestSystem__AnswerAssignment_6_3_1");
			builder.put(grammarAccess.getStructAccess().getFieldsAssignment_3_1(), "rule__Struct__FieldsAssignment_3_1");
			builder.put(grammarAccess.getAnswerAccess().getStatusAssignment_3_1(), "rule__Answer__StatusAssignment_3_1");
			builder.put(grammarAccess.getAnswerAccess().getReturnAssignment_4_1(), "rule__Answer__ReturnAssignment_4_1");
			builder.put(grammarAccess.getRouteAccess().getSegmentAssignment_4(), "rule__Route__SegmentAssignment_4");
			builder.put(grammarAccess.getRouteAccess().getSegmentAssignment_5_1(), "rule__Route__SegmentAssignment_5_1");
			builder.put(grammarAccess.getReGetAccess().getOpsAssignment_2_2(), "rule__ReGet__OpsAssignment_2_2");
			builder.put(grammarAccess.getReGetAccess().getOpsAssignment_2_3_1(), "rule__ReGet__OpsAssignment_2_3_1");
			builder.put(grammarAccess.getReGetAccess().getSuccAnswerAssignment_4(), "rule__ReGet__SuccAnswerAssignment_4");
			builder.put(grammarAccess.getReGetAccess().getRouteAssignment_6(), "rule__ReGet__RouteAssignment_6");
			builder.put(grammarAccess.getReGetAccess().getDataAssignment_7_2(), "rule__ReGet__DataAssignment_7_2");
			builder.put(grammarAccess.getReGetAccess().getDataAssignment_7_3_1(), "rule__ReGet__DataAssignment_7_3_1");
			builder.put(grammarAccess.getRePostAccess().getOpsAssignment_2_2(), "rule__RePost__OpsAssignment_2_2");
			builder.put(grammarAccess.getRePostAccess().getOpsAssignment_2_3_1(), "rule__RePost__OpsAssignment_2_3_1");
			builder.put(grammarAccess.getRePostAccess().getSuccAnswerAssignment_4(), "rule__RePost__SuccAnswerAssignment_4");
			builder.put(grammarAccess.getRePostAccess().getRouteAssignment_6(), "rule__RePost__RouteAssignment_6");
			builder.put(grammarAccess.getRePostAccess().getDataAssignment_7_2(), "rule__RePost__DataAssignment_7_2");
			builder.put(grammarAccess.getRePostAccess().getDataAssignment_7_3_1(), "rule__RePost__DataAssignment_7_3_1");
			builder.put(grammarAccess.getRePutAccess().getOpsAssignment_2_2(), "rule__RePut__OpsAssignment_2_2");
			builder.put(grammarAccess.getRePutAccess().getOpsAssignment_2_3_1(), "rule__RePut__OpsAssignment_2_3_1");
			builder.put(grammarAccess.getRePutAccess().getSuccAnswerAssignment_4(), "rule__RePut__SuccAnswerAssignment_4");
			builder.put(grammarAccess.getRePutAccess().getRouteAssignment_6(), "rule__RePut__RouteAssignment_6");
			builder.put(grammarAccess.getRePutAccess().getDataAssignment_7_2(), "rule__RePut__DataAssignment_7_2");
			builder.put(grammarAccess.getRePutAccess().getDataAssignment_7_3_1(), "rule__RePut__DataAssignment_7_3_1");
			builder.put(grammarAccess.getReDeleteAccess().getOpsAssignment_2_2(), "rule__ReDelete__OpsAssignment_2_2");
			builder.put(grammarAccess.getReDeleteAccess().getOpsAssignment_2_3_1(), "rule__ReDelete__OpsAssignment_2_3_1");
			builder.put(grammarAccess.getReDeleteAccess().getSuccAnswerAssignment_4(), "rule__ReDelete__SuccAnswerAssignment_4");
			builder.put(grammarAccess.getReDeleteAccess().getRouteAssignment_6(), "rule__ReDelete__RouteAssignment_6");
			builder.put(grammarAccess.getReDeleteAccess().getDataAssignment_7_2(), "rule__ReDelete__DataAssignment_7_2");
			builder.put(grammarAccess.getReDeleteAccess().getDataAssignment_7_3_1(), "rule__ReDelete__DataAssignment_7_3_1");
			builder.put(grammarAccess.getSegmentAccess().getValueAssignment_3_1(), "rule__Segment__ValueAssignment_3_1");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_2(), "rule__Parameter__NameAssignment_2");
			builder.put(grammarAccess.getAttachmentsAccess().getNameAssignment_2(), "rule__Attachments__NameAssignment_2");
			builder.put(grammarAccess.getRandomAccess().getNameAssignment_2(), "rule__Random__NameAssignment_2");
			builder.put(grammarAccess.getOpCreateAccess().getIdAssignment_2_1(), "rule__OpCreate__IdAssignment_2_1");
			builder.put(grammarAccess.getOpCreateAccess().getFailedAnswerAssignment_4(), "rule__OpCreate__FailedAnswerAssignment_4");
			builder.put(grammarAccess.getOpCreateAccess().getStructAssignment_6(), "rule__OpCreate__StructAssignment_6");
			builder.put(grammarAccess.getOpCreateAccess().getFieldsetAssignment_7_2(), "rule__OpCreate__FieldsetAssignment_7_2");
			builder.put(grammarAccess.getOpCreateAccess().getFieldsetAssignment_7_3_1(), "rule__OpCreate__FieldsetAssignment_7_3_1");
			builder.put(grammarAccess.getOpReadAccess().getIdAssignment_2_1(), "rule__OpRead__IdAssignment_2_1");
			builder.put(grammarAccess.getOpReadAccess().getFailedAnswerAssignment_4(), "rule__OpRead__FailedAnswerAssignment_4");
			builder.put(grammarAccess.getOpReadAccess().getStructAssignment_6(), "rule__OpRead__StructAssignment_6");
			builder.put(grammarAccess.getOpReadAccess().getFieldAssignment_7_2(), "rule__OpRead__FieldAssignment_7_2");
			builder.put(grammarAccess.getOpReadAccess().getFieldAssignment_7_3_1(), "rule__OpRead__FieldAssignment_7_3_1");
			builder.put(grammarAccess.getOpUpdateAccess().getIdAssignment_2_1(), "rule__OpUpdate__IdAssignment_2_1");
			builder.put(grammarAccess.getOpUpdateAccess().getFailedAnswerAssignment_4(), "rule__OpUpdate__FailedAnswerAssignment_4");
			builder.put(grammarAccess.getOpUpdateAccess().getStructAssignment_6(), "rule__OpUpdate__StructAssignment_6");
			builder.put(grammarAccess.getOpUpdateAccess().getFieldsetAssignment_7_2(), "rule__OpUpdate__FieldsetAssignment_7_2");
			builder.put(grammarAccess.getOpUpdateAccess().getFieldsetAssignment_7_3_1(), "rule__OpUpdate__FieldsetAssignment_7_3_1");
			builder.put(grammarAccess.getOpDeleteAccess().getIdAssignment_2_1(), "rule__OpDelete__IdAssignment_2_1");
			builder.put(grammarAccess.getOpDeleteAccess().getFailedAnswerAssignment_4(), "rule__OpDelete__FailedAnswerAssignment_4");
			builder.put(grammarAccess.getOpDeleteAccess().getStructAssignment_6(), "rule__OpDelete__StructAssignment_6");
			builder.put(grammarAccess.getFieldSetAccess().getNameAssignment_2(), "rule__FieldSet__NameAssignment_2");
			builder.put(grammarAccess.getFieldSetAccess().getExprAssignment_4_1(), "rule__FieldSet__ExprAssignment_4_1");
			builder.put(grammarAccess.getFieldAccess().getNameAssignment_2(), "rule__Field__NameAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private RestGrammarAccess grammarAccess;

	@Override
	protected InternalRestParser createParser() {
		InternalRestParser result = new InternalRestParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RestGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RestGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
