/*
 * generated by Xtext 2.25.0
 */
package rest.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import rest.ui.internal.RestActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RestExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(RestActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		RestActivator activator = RestActivator.getInstance();
		return activator != null ? activator.getInjector(RestActivator.REST_REST) : null;
	}

}
