/*
 * generated by Xtext 2.25.0
 */
package rest.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRestScopeProvider extends DelegatingScopeProvider {
}
