/*
 * generated by Xtext 2.25.0
 */
package rest.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import rest.ide.contentassist.antlr.internal.InternalRestParser;
import rest.services.RestGrammarAccess;

public class RestParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(RestGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, RestGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRequestAccess().getAlternatives(), "rule__Request__Alternatives");
			builder.put(grammarAccess.getOperationAccess().getAlternatives(), "rule__Operation__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getRestSystemAccess().getGroup(), "rule__RestSystem__Group__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_3(), "rule__RestSystem__Group_3__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_3_3(), "rule__RestSystem__Group_3_3__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_4(), "rule__RestSystem__Group_4__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_4_3(), "rule__RestSystem__Group_4_3__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_5(), "rule__RestSystem__Group_5__0");
			builder.put(grammarAccess.getRestSystemAccess().getGroup_5_3(), "rule__RestSystem__Group_5_3__0");
			builder.put(grammarAccess.getStructAccess().getGroup(), "rule__Struct__Group__0");
			builder.put(grammarAccess.getStructAccess().getGroup_4(), "rule__Struct__Group_4__0");
			builder.put(grammarAccess.getStructAccess().getGroup_4_3(), "rule__Struct__Group_4_3__0");
			builder.put(grammarAccess.getAnswerAccess().getGroup(), "rule__Answer__Group__0");
			builder.put(grammarAccess.getAnswerAccess().getGroup_5(), "rule__Answer__Group_5__0");
			builder.put(grammarAccess.getRouteAccess().getGroup(), "rule__Route__Group__0");
			builder.put(grammarAccess.getRouteAccess().getGroup_5(), "rule__Route__Group_5__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getReGetAccess().getGroup(), "rule__ReGet__Group__0");
			builder.put(grammarAccess.getReGetAccess().getGroup_6(), "rule__ReGet__Group_6__0");
			builder.put(grammarAccess.getReGetAccess().getGroup_6_3(), "rule__ReGet__Group_6_3__0");
			builder.put(grammarAccess.getReGetAccess().getGroup_7(), "rule__ReGet__Group_7__0");
			builder.put(grammarAccess.getReGetAccess().getGroup_7_3(), "rule__ReGet__Group_7_3__0");
			builder.put(grammarAccess.getRePostAccess().getGroup(), "rule__RePost__Group__0");
			builder.put(grammarAccess.getRePostAccess().getGroup_6(), "rule__RePost__Group_6__0");
			builder.put(grammarAccess.getRePostAccess().getGroup_6_3(), "rule__RePost__Group_6_3__0");
			builder.put(grammarAccess.getRePostAccess().getGroup_7(), "rule__RePost__Group_7__0");
			builder.put(grammarAccess.getRePostAccess().getGroup_7_3(), "rule__RePost__Group_7_3__0");
			builder.put(grammarAccess.getRePutAccess().getGroup(), "rule__RePut__Group__0");
			builder.put(grammarAccess.getRePutAccess().getGroup_6(), "rule__RePut__Group_6__0");
			builder.put(grammarAccess.getRePutAccess().getGroup_6_3(), "rule__RePut__Group_6_3__0");
			builder.put(grammarAccess.getRePutAccess().getGroup_7(), "rule__RePut__Group_7__0");
			builder.put(grammarAccess.getRePutAccess().getGroup_7_3(), "rule__RePut__Group_7_3__0");
			builder.put(grammarAccess.getReDeleteAccess().getGroup(), "rule__ReDelete__Group__0");
			builder.put(grammarAccess.getReDeleteAccess().getGroup_6(), "rule__ReDelete__Group_6__0");
			builder.put(grammarAccess.getReDeleteAccess().getGroup_6_3(), "rule__ReDelete__Group_6_3__0");
			builder.put(grammarAccess.getReDeleteAccess().getGroup_7(), "rule__ReDelete__Group_7__0");
			builder.put(grammarAccess.getReDeleteAccess().getGroup_7_3(), "rule__ReDelete__Group_7_3__0");
			builder.put(grammarAccess.getSegmentAccess().getGroup(), "rule__Segment__Group__0");
			builder.put(grammarAccess.getSegmentAccess().getGroup_3(), "rule__Segment__Group_3__0");
			builder.put(grammarAccess.getOpCreateAccess().getGroup(), "rule__OpCreate__Group__0");
			builder.put(grammarAccess.getOpCreateAccess().getGroup_2(), "rule__OpCreate__Group_2__0");
			builder.put(grammarAccess.getOpCreateAccess().getGroup_7(), "rule__OpCreate__Group_7__0");
			builder.put(grammarAccess.getOpCreateAccess().getGroup_7_3(), "rule__OpCreate__Group_7_3__0");
			builder.put(grammarAccess.getOpReadAccess().getGroup(), "rule__OpRead__Group__0");
			builder.put(grammarAccess.getOpReadAccess().getGroup_2(), "rule__OpRead__Group_2__0");
			builder.put(grammarAccess.getOpReadAccess().getGroup_7(), "rule__OpRead__Group_7__0");
			builder.put(grammarAccess.getOpReadAccess().getGroup_7_3(), "rule__OpRead__Group_7_3__0");
			builder.put(grammarAccess.getOpUpdateAccess().getGroup(), "rule__OpUpdate__Group__0");
			builder.put(grammarAccess.getOpUpdateAccess().getGroup_2(), "rule__OpUpdate__Group_2__0");
			builder.put(grammarAccess.getOpUpdateAccess().getGroup_7(), "rule__OpUpdate__Group_7__0");
			builder.put(grammarAccess.getOpUpdateAccess().getGroup_7_3(), "rule__OpUpdate__Group_7_3__0");
			builder.put(grammarAccess.getOpDeleteAccess().getGroup(), "rule__OpDelete__Group__0");
			builder.put(grammarAccess.getOpDeleteAccess().getGroup_2(), "rule__OpDelete__Group_2__0");
			builder.put(grammarAccess.getFieldSetAccess().getGroup(), "rule__FieldSet__Group__0");
			builder.put(grammarAccess.getFieldSetAccess().getGroup_4(), "rule__FieldSet__Group_4__0");
			builder.put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getRestSystemAccess().getRequestsAssignment_3_2(), "rule__RestSystem__RequestsAssignment_3_2");
			builder.put(grammarAccess.getRestSystemAccess().getRequestsAssignment_3_3_1(), "rule__RestSystem__RequestsAssignment_3_3_1");
			builder.put(grammarAccess.getRestSystemAccess().getStructsAssignment_4_2(), "rule__RestSystem__StructsAssignment_4_2");
			builder.put(grammarAccess.getRestSystemAccess().getStructsAssignment_4_3_1(), "rule__RestSystem__StructsAssignment_4_3_1");
			builder.put(grammarAccess.getRestSystemAccess().getAnswersAssignment_5_2(), "rule__RestSystem__AnswersAssignment_5_2");
			builder.put(grammarAccess.getRestSystemAccess().getAnswersAssignment_5_3_1(), "rule__RestSystem__AnswersAssignment_5_3_1");
			builder.put(grammarAccess.getStructAccess().getNameAssignment_2(), "rule__Struct__NameAssignment_2");
			builder.put(grammarAccess.getStructAccess().getFieldsAssignment_4_2(), "rule__Struct__FieldsAssignment_4_2");
			builder.put(grammarAccess.getStructAccess().getFieldsAssignment_4_3_1(), "rule__Struct__FieldsAssignment_4_3_1");
			builder.put(grammarAccess.getAnswerAccess().getNameAssignment_1(), "rule__Answer__NameAssignment_1");
			builder.put(grammarAccess.getAnswerAccess().getStatusAssignment_4(), "rule__Answer__StatusAssignment_4");
			builder.put(grammarAccess.getAnswerAccess().getReturnAssignment_5_1(), "rule__Answer__ReturnAssignment_5_1");
			builder.put(grammarAccess.getRouteAccess().getSegmentsAssignment_4(), "rule__Route__SegmentsAssignment_4");
			builder.put(grammarAccess.getRouteAccess().getSegmentsAssignment_5_1(), "rule__Route__SegmentsAssignment_5_1");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_2(), "rule__Parameter__NameAssignment_2");
			builder.put(grammarAccess.getReGetAccess().getSuccAnswerAssignment_3(), "rule__ReGet__SuccAnswerAssignment_3");
			builder.put(grammarAccess.getReGetAccess().getRouteAssignment_5(), "rule__ReGet__RouteAssignment_5");
			builder.put(grammarAccess.getReGetAccess().getOperationsAssignment_6_2(), "rule__ReGet__OperationsAssignment_6_2");
			builder.put(grammarAccess.getReGetAccess().getOperationsAssignment_6_3_1(), "rule__ReGet__OperationsAssignment_6_3_1");
			builder.put(grammarAccess.getReGetAccess().getParametersAssignment_7_2(), "rule__ReGet__ParametersAssignment_7_2");
			builder.put(grammarAccess.getReGetAccess().getParametersAssignment_7_3_1(), "rule__ReGet__ParametersAssignment_7_3_1");
			builder.put(grammarAccess.getRePostAccess().getSuccAnswerAssignment_3(), "rule__RePost__SuccAnswerAssignment_3");
			builder.put(grammarAccess.getRePostAccess().getRouteAssignment_5(), "rule__RePost__RouteAssignment_5");
			builder.put(grammarAccess.getRePostAccess().getOperationsAssignment_6_2(), "rule__RePost__OperationsAssignment_6_2");
			builder.put(grammarAccess.getRePostAccess().getOperationsAssignment_6_3_1(), "rule__RePost__OperationsAssignment_6_3_1");
			builder.put(grammarAccess.getRePostAccess().getParametersAssignment_7_2(), "rule__RePost__ParametersAssignment_7_2");
			builder.put(grammarAccess.getRePostAccess().getParametersAssignment_7_3_1(), "rule__RePost__ParametersAssignment_7_3_1");
			builder.put(grammarAccess.getRePutAccess().getSuccAnswerAssignment_3(), "rule__RePut__SuccAnswerAssignment_3");
			builder.put(grammarAccess.getRePutAccess().getRouteAssignment_5(), "rule__RePut__RouteAssignment_5");
			builder.put(grammarAccess.getRePutAccess().getOperationsAssignment_6_2(), "rule__RePut__OperationsAssignment_6_2");
			builder.put(grammarAccess.getRePutAccess().getOperationsAssignment_6_3_1(), "rule__RePut__OperationsAssignment_6_3_1");
			builder.put(grammarAccess.getRePutAccess().getParametersAssignment_7_2(), "rule__RePut__ParametersAssignment_7_2");
			builder.put(grammarAccess.getRePutAccess().getParametersAssignment_7_3_1(), "rule__RePut__ParametersAssignment_7_3_1");
			builder.put(grammarAccess.getReDeleteAccess().getSuccAnswerAssignment_3(), "rule__ReDelete__SuccAnswerAssignment_3");
			builder.put(grammarAccess.getReDeleteAccess().getRouteAssignment_5(), "rule__ReDelete__RouteAssignment_5");
			builder.put(grammarAccess.getReDeleteAccess().getOperationsAssignment_6_2(), "rule__ReDelete__OperationsAssignment_6_2");
			builder.put(grammarAccess.getReDeleteAccess().getOperationsAssignment_6_3_1(), "rule__ReDelete__OperationsAssignment_6_3_1");
			builder.put(grammarAccess.getReDeleteAccess().getParametersAssignment_7_2(), "rule__ReDelete__ParametersAssignment_7_2");
			builder.put(grammarAccess.getReDeleteAccess().getParametersAssignment_7_3_1(), "rule__ReDelete__ParametersAssignment_7_3_1");
			builder.put(grammarAccess.getSegmentAccess().getValueAssignment_3_1(), "rule__Segment__ValueAssignment_3_1");
			builder.put(grammarAccess.getOpCreateAccess().getIdAssignment_2_1(), "rule__OpCreate__IdAssignment_2_1");
			builder.put(grammarAccess.getOpCreateAccess().getFailedAnswerAssignment_4(), "rule__OpCreate__FailedAnswerAssignment_4");
			builder.put(grammarAccess.getOpCreateAccess().getStructAssignment_6(), "rule__OpCreate__StructAssignment_6");
			builder.put(grammarAccess.getOpCreateAccess().getFieldsetsAssignment_7_2(), "rule__OpCreate__FieldsetsAssignment_7_2");
			builder.put(grammarAccess.getOpCreateAccess().getFieldsetsAssignment_7_3_1(), "rule__OpCreate__FieldsetsAssignment_7_3_1");
			builder.put(grammarAccess.getOpReadAccess().getIdAssignment_2_1(), "rule__OpRead__IdAssignment_2_1");
			builder.put(grammarAccess.getOpReadAccess().getFailedAnswerAssignment_4(), "rule__OpRead__FailedAnswerAssignment_4");
			builder.put(grammarAccess.getOpReadAccess().getStructAssignment_6(), "rule__OpRead__StructAssignment_6");
			builder.put(grammarAccess.getOpReadAccess().getFieldsAssignment_7_2(), "rule__OpRead__FieldsAssignment_7_2");
			builder.put(grammarAccess.getOpReadAccess().getFieldsAssignment_7_3_1(), "rule__OpRead__FieldsAssignment_7_3_1");
			builder.put(grammarAccess.getOpUpdateAccess().getIdAssignment_2_1(), "rule__OpUpdate__IdAssignment_2_1");
			builder.put(grammarAccess.getOpUpdateAccess().getFailedAnswerAssignment_4(), "rule__OpUpdate__FailedAnswerAssignment_4");
			builder.put(grammarAccess.getOpUpdateAccess().getStructAssignment_6(), "rule__OpUpdate__StructAssignment_6");
			builder.put(grammarAccess.getOpUpdateAccess().getFieldsetsAssignment_7_2(), "rule__OpUpdate__FieldsetsAssignment_7_2");
			builder.put(grammarAccess.getOpUpdateAccess().getFieldsetsAssignment_7_3_1(), "rule__OpUpdate__FieldsetsAssignment_7_3_1");
			builder.put(grammarAccess.getOpDeleteAccess().getIdAssignment_2_1(), "rule__OpDelete__IdAssignment_2_1");
			builder.put(grammarAccess.getOpDeleteAccess().getFailedAnswerAssignment_4(), "rule__OpDelete__FailedAnswerAssignment_4");
			builder.put(grammarAccess.getOpDeleteAccess().getStructAssignment_6(), "rule__OpDelete__StructAssignment_6");
			builder.put(grammarAccess.getFieldSetAccess().getNameAssignment_2(), "rule__FieldSet__NameAssignment_2");
			builder.put(grammarAccess.getFieldSetAccess().getValueAssignment_4_1(), "rule__FieldSet__ValueAssignment_4_1");
			builder.put(grammarAccess.getFieldAccess().getNameAssignment_2(), "rule__Field__NameAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private RestGrammarAccess grammarAccess;

	@Override
	protected InternalRestParser createParser() {
		InternalRestParser result = new InternalRestParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RestGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RestGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
