/*
 * generated by Xtext 2.25.0
 */
package rest.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import rest.parser.antlr.internal.InternalRestParser;
import rest.services.RestGrammarAccess;

public class RestParser extends AbstractAntlrParser {

	@Inject
	private RestGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRestParser createParser(XtextTokenStream stream) {
		return new InternalRestParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RestSystem";
	}

	public RestGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RestGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
