/*
 * generated by Xtext 2.25.0
 */
package rest;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RestStandaloneSetup extends RestStandaloneSetupGenerated {

	public static void doSetup() {
		new RestStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
