/*
 * generated by Xtext 2.25.0
 */
package rest.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RestGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class RestSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.RestSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRestSystemAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRestSystemKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRequestKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cRequestAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cRequestRequestParserRuleCall_3_2_0 = (RuleCall)cRequestAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cRequestAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cRequestRequestParserRuleCall_3_3_1_0 = (RuleCall)cRequestAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//RestSystem returns RestSystem:
		//    {RestSystem}
		//    'RestSystem'
		//    '{'
		//        ('request' '{' request+=Request ( "," request+=Request)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RestSystem}
		//'RestSystem'
		//'{'
		//    ('request' '{' request+=Request ( "," request+=Request)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{RestSystem}
		public Action getRestSystemAction_0() { return cRestSystemAction_0; }
		
		//'RestSystem'
		public Keyword getRestSystemKeyword_1() { return cRestSystemKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('request' '{' request+=Request ( "," request+=Request)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'request'
		public Keyword getRequestKeyword_3_0() { return cRequestKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//request+=Request
		public Assignment getRequestAssignment_3_2() { return cRequestAssignment_3_2; }
		
		//Request
		public RuleCall getRequestRequestParserRuleCall_3_2_0() { return cRequestRequestParserRuleCall_3_2_0; }
		
		//( "," request+=Request)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//request+=Request
		public Assignment getRequestAssignment_3_3_1() { return cRequestAssignment_3_3_1; }
		
		//Request
		public RuleCall getRequestRequestParserRuleCall_3_3_1_0() { return cRequestRequestParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class RequestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Request");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cReGetParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRePostParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRePutParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cReDeleteParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Request returns Request:
		//    ReGet | RePost | RePut | ReDelete;
		@Override public ParserRule getRule() { return rule; }
		
		//ReGet | RePost | RePut | ReDelete
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ReGet
		public RuleCall getReGetParserRuleCall_0() { return cReGetParserRuleCall_0; }
		
		//RePost
		public RuleCall getRePostParserRuleCall_1() { return cRePostParserRuleCall_1; }
		
		//RePut
		public RuleCall getRePutParserRuleCall_2() { return cRePutParserRuleCall_2; }
		
		//ReDelete
		public RuleCall getReDeleteParserRuleCall_3() { return cReDeleteParserRuleCall_3; }
	}
	public class DataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Data");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cParameterParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAttachmentsParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRandomParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Data returns Data:
		//    Parameter | Attachments | Random;
		@Override public ParserRule getRule() { return rule; }
		
		//Parameter | Attachments | Random
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Parameter
		public RuleCall getParameterParserRuleCall_0() { return cParameterParserRuleCall_0; }
		
		//Attachments
		public RuleCall getAttachmentsParserRuleCall_1() { return cAttachmentsParserRuleCall_1; }
		
		//Random
		public RuleCall getRandomParserRuleCall_2() { return cRandomParserRuleCall_2; }
	}
	public class OperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Operation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cOpCreateParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOpReadParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cOpUpdateParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cOpDeleteParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Operation returns Operation:
		//    OpCreate | OpRead | OpUpdate | OpDelete;
		@Override public ParserRule getRule() { return rule; }
		
		//OpCreate | OpRead | OpUpdate | OpDelete
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//OpCreate
		public RuleCall getOpCreateParserRuleCall_0() { return cOpCreateParserRuleCall_0; }
		
		//OpRead
		public RuleCall getOpReadParserRuleCall_1() { return cOpReadParserRuleCall_1; }
		
		//OpUpdate
		public RuleCall getOpUpdateParserRuleCall_2() { return cOpUpdateParserRuleCall_2; }
		
		//OpDelete
		public RuleCall getOpDeleteParserRuleCall_3() { return cOpDeleteParserRuleCall_3; }
	}
	public class RouteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Route");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRouteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSegmentKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSegmentAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSegmentSegmentParserRuleCall_4_0 = (RuleCall)cSegmentAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSegmentAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cSegmentSegmentParserRuleCall_5_1_0 = (RuleCall)cSegmentAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Route returns Route:
		//    'Route'
		//    '{'
		//        'segment' '{' segment+=Segment ( "," segment+=Segment)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Route'
		//'{'
		//    'segment' '{' segment+=Segment ( "," segment+=Segment)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Route'
		public Keyword getRouteKeyword_0() { return cRouteKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'segment'
		public Keyword getSegmentKeyword_2() { return cSegmentKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//segment+=Segment
		public Assignment getSegmentAssignment_4() { return cSegmentAssignment_4; }
		
		//Segment
		public RuleCall getSegmentSegmentParserRuleCall_4_0() { return cSegmentSegmentParserRuleCall_4_0; }
		
		//( "," segment+=Segment)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//segment+=Segment
		public Assignment getSegmentAssignment_5_1() { return cSegmentAssignment_5_1; }
		
		//Segment
		public RuleCall getSegmentSegmentParserRuleCall_5_1_0() { return cSegmentSegmentParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ReGetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.ReGet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReGetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRouteKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRouteAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRouteRouteParserRuleCall_3_0 = (RuleCall)cRouteAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDataAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDataDataParserRuleCall_4_2_0 = (RuleCall)cDataAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDataAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cDataDataParserRuleCall_4_3_1_0 = (RuleCall)cDataAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOpsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOpsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cOpsOperationParserRuleCall_5_2_0 = (RuleCall)cOpsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOpsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cOpsOperationParserRuleCall_5_3_1_0 = (RuleCall)cOpsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ReGet returns ReGet:
		//    'ReGet'
		//    '{'
		//        'route' route=Route
		//        ('data' '{' data+=Data ( "," data+=Data)* '}' )?
		//        ('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ReGet'
		//'{'
		//    'route' route=Route
		//    ('data' '{' data+=Data ( "," data+=Data)* '}' )?
		//    ('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ReGet'
		public Keyword getReGetKeyword_0() { return cReGetKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'route'
		public Keyword getRouteKeyword_2() { return cRouteKeyword_2; }
		
		//route=Route
		public Assignment getRouteAssignment_3() { return cRouteAssignment_3; }
		
		//Route
		public RuleCall getRouteRouteParserRuleCall_3_0() { return cRouteRouteParserRuleCall_3_0; }
		
		//('data' '{' data+=Data ( "," data+=Data)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'data'
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//data+=Data
		public Assignment getDataAssignment_4_2() { return cDataAssignment_4_2; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_4_2_0() { return cDataDataParserRuleCall_4_2_0; }
		
		//( "," data+=Data)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//data+=Data
		public Assignment getDataAssignment_4_3_1() { return cDataAssignment_4_3_1; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_4_3_1_0() { return cDataDataParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ops'
		public Keyword getOpsKeyword_5_0() { return cOpsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//ops+=Operation
		public Assignment getOpsAssignment_5_2() { return cOpsAssignment_5_2; }
		
		//Operation
		public RuleCall getOpsOperationParserRuleCall_5_2_0() { return cOpsOperationParserRuleCall_5_2_0; }
		
		//( "," ops+=Operation)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//ops+=Operation
		public Assignment getOpsAssignment_5_3_1() { return cOpsAssignment_5_3_1; }
		
		//Operation
		public RuleCall getOpsOperationParserRuleCall_5_3_1_0() { return cOpsOperationParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class RePostElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.RePost");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRePostKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRouteKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRouteAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRouteRouteParserRuleCall_3_0 = (RuleCall)cRouteAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDataAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDataDataParserRuleCall_4_2_0 = (RuleCall)cDataAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDataAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cDataDataParserRuleCall_4_3_1_0 = (RuleCall)cDataAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOpsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOpsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cOpsOperationParserRuleCall_5_2_0 = (RuleCall)cOpsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOpsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cOpsOperationParserRuleCall_5_3_1_0 = (RuleCall)cOpsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//RePost returns RePost:
		//    'RePost'
		//    '{'
		//        'route' route=Route
		//        ('data' '{' data+=Data ( "," data+=Data)* '}' )?
		//        ('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'RePost'
		//'{'
		//    'route' route=Route
		//    ('data' '{' data+=Data ( "," data+=Data)* '}' )?
		//    ('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'RePost'
		public Keyword getRePostKeyword_0() { return cRePostKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'route'
		public Keyword getRouteKeyword_2() { return cRouteKeyword_2; }
		
		//route=Route
		public Assignment getRouteAssignment_3() { return cRouteAssignment_3; }
		
		//Route
		public RuleCall getRouteRouteParserRuleCall_3_0() { return cRouteRouteParserRuleCall_3_0; }
		
		//('data' '{' data+=Data ( "," data+=Data)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'data'
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//data+=Data
		public Assignment getDataAssignment_4_2() { return cDataAssignment_4_2; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_4_2_0() { return cDataDataParserRuleCall_4_2_0; }
		
		//( "," data+=Data)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//data+=Data
		public Assignment getDataAssignment_4_3_1() { return cDataAssignment_4_3_1; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_4_3_1_0() { return cDataDataParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ops'
		public Keyword getOpsKeyword_5_0() { return cOpsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//ops+=Operation
		public Assignment getOpsAssignment_5_2() { return cOpsAssignment_5_2; }
		
		//Operation
		public RuleCall getOpsOperationParserRuleCall_5_2_0() { return cOpsOperationParserRuleCall_5_2_0; }
		
		//( "," ops+=Operation)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//ops+=Operation
		public Assignment getOpsAssignment_5_3_1() { return cOpsAssignment_5_3_1; }
		
		//Operation
		public RuleCall getOpsOperationParserRuleCall_5_3_1_0() { return cOpsOperationParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class RePutElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.RePut");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRePutKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRouteKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRouteAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRouteRouteParserRuleCall_3_0 = (RuleCall)cRouteAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDataAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDataDataParserRuleCall_4_2_0 = (RuleCall)cDataAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDataAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cDataDataParserRuleCall_4_3_1_0 = (RuleCall)cDataAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOpsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOpsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cOpsOperationParserRuleCall_5_2_0 = (RuleCall)cOpsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOpsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cOpsOperationParserRuleCall_5_3_1_0 = (RuleCall)cOpsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//RePut returns RePut:
		//    'RePut'
		//    '{'
		//        'route' route=Route
		//        ('data' '{' data+=Data ( "," data+=Data)* '}' )?
		//        ('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'RePut'
		//'{'
		//    'route' route=Route
		//    ('data' '{' data+=Data ( "," data+=Data)* '}' )?
		//    ('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'RePut'
		public Keyword getRePutKeyword_0() { return cRePutKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'route'
		public Keyword getRouteKeyword_2() { return cRouteKeyword_2; }
		
		//route=Route
		public Assignment getRouteAssignment_3() { return cRouteAssignment_3; }
		
		//Route
		public RuleCall getRouteRouteParserRuleCall_3_0() { return cRouteRouteParserRuleCall_3_0; }
		
		//('data' '{' data+=Data ( "," data+=Data)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'data'
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//data+=Data
		public Assignment getDataAssignment_4_2() { return cDataAssignment_4_2; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_4_2_0() { return cDataDataParserRuleCall_4_2_0; }
		
		//( "," data+=Data)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//data+=Data
		public Assignment getDataAssignment_4_3_1() { return cDataAssignment_4_3_1; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_4_3_1_0() { return cDataDataParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ops'
		public Keyword getOpsKeyword_5_0() { return cOpsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//ops+=Operation
		public Assignment getOpsAssignment_5_2() { return cOpsAssignment_5_2; }
		
		//Operation
		public RuleCall getOpsOperationParserRuleCall_5_2_0() { return cOpsOperationParserRuleCall_5_2_0; }
		
		//( "," ops+=Operation)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//ops+=Operation
		public Assignment getOpsAssignment_5_3_1() { return cOpsAssignment_5_3_1; }
		
		//Operation
		public RuleCall getOpsOperationParserRuleCall_5_3_1_0() { return cOpsOperationParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ReDeleteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.ReDelete");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReDeleteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRouteKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRouteAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRouteRouteParserRuleCall_3_0 = (RuleCall)cRouteAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDataAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDataDataParserRuleCall_4_2_0 = (RuleCall)cDataAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDataAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cDataDataParserRuleCall_4_3_1_0 = (RuleCall)cDataAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOpsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOpsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cOpsOperationParserRuleCall_5_2_0 = (RuleCall)cOpsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOpsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cOpsOperationParserRuleCall_5_3_1_0 = (RuleCall)cOpsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ReDelete returns ReDelete:
		//    'ReDelete'
		//    '{'
		//        'route' route=Route
		//        ('data' '{' data+=Data ( "," data+=Data)* '}' )?
		//        ('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ReDelete'
		//'{'
		//    'route' route=Route
		//    ('data' '{' data+=Data ( "," data+=Data)* '}' )?
		//    ('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ReDelete'
		public Keyword getReDeleteKeyword_0() { return cReDeleteKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'route'
		public Keyword getRouteKeyword_2() { return cRouteKeyword_2; }
		
		//route=Route
		public Assignment getRouteAssignment_3() { return cRouteAssignment_3; }
		
		//Route
		public RuleCall getRouteRouteParserRuleCall_3_0() { return cRouteRouteParserRuleCall_3_0; }
		
		//('data' '{' data+=Data ( "," data+=Data)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'data'
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//data+=Data
		public Assignment getDataAssignment_4_2() { return cDataAssignment_4_2; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_4_2_0() { return cDataDataParserRuleCall_4_2_0; }
		
		//( "," data+=Data)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//data+=Data
		public Assignment getDataAssignment_4_3_1() { return cDataAssignment_4_3_1; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_4_3_1_0() { return cDataDataParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ops'
		public Keyword getOpsKeyword_5_0() { return cOpsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//ops+=Operation
		public Assignment getOpsAssignment_5_2() { return cOpsAssignment_5_2; }
		
		//Operation
		public RuleCall getOpsOperationParserRuleCall_5_2_0() { return cOpsOperationParserRuleCall_5_2_0; }
		
		//( "," ops+=Operation)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//ops+=Operation
		public Assignment getOpsAssignment_5_3_1() { return cOpsAssignment_5_3_1; }
		
		//Operation
		public RuleCall getOpsOperationParserRuleCall_5_3_1_0() { return cOpsOperationParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class SegmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Segment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSegmentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSegmentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Segment returns Segment:
		//    {Segment}
		//    'Segment'
		//    '{'
		//        ('value' value=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Segment}
		//'Segment'
		//'{'
		//    ('value' value=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Segment}
		public Action getSegmentAction_0() { return cSegmentAction_0; }
		
		//'Segment'
		public Keyword getSegmentKeyword_1() { return cSegmentKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('value' value=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'value'
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }
		
		//value=EString
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_3_1_0() { return cValueEStringParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParameterAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cParameterKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Parameter returns Parameter:
		//    {Parameter}
		//    'Parameter'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Parameter}
		//'Parameter'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Parameter}
		public Action getParameterAction_0() { return cParameterAction_0; }
		
		//'Parameter'
		public Keyword getParameterKeyword_1() { return cParameterKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class AttachmentsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Attachments");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAttachmentsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAttachmentsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Attachments returns Attachments:
		//    {Attachments}
		//    'Attachments'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Attachments}
		//'Attachments'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Attachments}
		public Action getAttachmentsAction_0() { return cAttachmentsAction_0; }
		
		//'Attachments'
		public Keyword getAttachmentsKeyword_1() { return cAttachmentsKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class RandomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Random");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRandomAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRandomKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Random returns Random:
		//    {Random}
		//    'Random'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Random}
		//'Random'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Random}
		public Action getRandomAction_0() { return cRandomAction_0; }
		
		//'Random'
		public Keyword getRandomKeyword_1() { return cRandomKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class AnswerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Answer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAnswerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAnswerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cStatusKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cStatusAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cStatusEIntParserRuleCall_3_1_0 = (RuleCall)cStatusAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cReturnKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cReturnAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cReturnEStringParserRuleCall_4_1_0 = (RuleCall)cReturnAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Answer returns Answer:
		//    {Answer}
		//    'Answer'
		//    '{'
		//        ('status' status=EInt)?
		//        ('return' return=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Answer}
		//'Answer'
		//'{'
		//    ('status' status=EInt)?
		//    ('return' return=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Answer}
		public Action getAnswerAction_0() { return cAnswerAction_0; }
		
		//'Answer'
		public Keyword getAnswerKeyword_1() { return cAnswerKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('status' status=EInt)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'status'
		public Keyword getStatusKeyword_3_0() { return cStatusKeyword_3_0; }
		
		//status=EInt
		public Assignment getStatusAssignment_3_1() { return cStatusAssignment_3_1; }
		
		//EInt
		public RuleCall getStatusEIntParserRuleCall_3_1_0() { return cStatusEIntParserRuleCall_3_1_0; }
		
		//('return' return=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'return'
		public Keyword getReturnKeyword_4_0() { return cReturnKeyword_4_0; }
		
		//return=EString
		public Assignment getReturnAssignment_4_1() { return cReturnAssignment_4_1; }
		
		//EString
		public RuleCall getReturnEStringParserRuleCall_4_1_0() { return cReturnEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class StructElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Struct");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStructAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStructKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFieldsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFieldsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cFieldsEStringParserRuleCall_3_1_0 = (RuleCall)cFieldsAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Struct returns Struct:
		//    {Struct}
		//    'Struct'
		//    '{'
		//        ('fields' fields=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Struct}
		//'Struct'
		//'{'
		//    ('fields' fields=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Struct}
		public Action getStructAction_0() { return cStructAction_0; }
		
		//'Struct'
		public Keyword getStructKeyword_1() { return cStructKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('fields' fields=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'fields'
		public Keyword getFieldsKeyword_3_0() { return cFieldsKeyword_3_0; }
		
		//fields=EString
		public Assignment getFieldsAssignment_3_1() { return cFieldsAssignment_3_1; }
		
		//EString
		public RuleCall getFieldsEStringParserRuleCall_3_1_0() { return cFieldsEStringParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class OpCreateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.OpCreate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpCreateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_2_1_0 = (RuleCall)cIdAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFailedAnswerKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFailedAnswerAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cFailedAnswerAnswerParserRuleCall_3_1_0 = (RuleCall)cFailedAnswerAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSuccAnswerKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSuccAnswerAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cSuccAnswerAnswerParserRuleCall_4_1_0 = (RuleCall)cSuccAnswerAssignment_4_1.eContents().get(0);
		private final Keyword cStructKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStructAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStructStructParserRuleCall_6_0 = (RuleCall)cStructAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cFieldsetKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cFieldsetAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cFieldsetFieldSetParserRuleCall_7_2_0 = (RuleCall)cFieldsetAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cFieldsetAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cFieldsetFieldSetParserRuleCall_7_3_1_0 = (RuleCall)cFieldsetAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//OpCreate returns OpCreate:
		//    'OpCreate'
		//    '{'
		//        ('id' id=EString)?
		//        ('failedAnswer' failedAnswer=Answer)?
		//        ('succAnswer' succAnswer=Answer)?
		//        'struct' struct=Struct
		//        ('fieldset' '{' fieldset+=FieldSet ( "," fieldset+=FieldSet)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'OpCreate'
		//'{'
		//    ('id' id=EString)?
		//    ('failedAnswer' failedAnswer=Answer)?
		//    ('succAnswer' succAnswer=Answer)?
		//    'struct' struct=Struct
		//    ('fieldset' '{' fieldset+=FieldSet ( "," fieldset+=FieldSet)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'OpCreate'
		public Keyword getOpCreateKeyword_0() { return cOpCreateKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('id' id=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'id'
		public Keyword getIdKeyword_2_0() { return cIdKeyword_2_0; }
		
		//id=EString
		public Assignment getIdAssignment_2_1() { return cIdAssignment_2_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_1_0() { return cIdEStringParserRuleCall_2_1_0; }
		
		//('failedAnswer' failedAnswer=Answer)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'failedAnswer'
		public Keyword getFailedAnswerKeyword_3_0() { return cFailedAnswerKeyword_3_0; }
		
		//failedAnswer=Answer
		public Assignment getFailedAnswerAssignment_3_1() { return cFailedAnswerAssignment_3_1; }
		
		//Answer
		public RuleCall getFailedAnswerAnswerParserRuleCall_3_1_0() { return cFailedAnswerAnswerParserRuleCall_3_1_0; }
		
		//('succAnswer' succAnswer=Answer)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'succAnswer'
		public Keyword getSuccAnswerKeyword_4_0() { return cSuccAnswerKeyword_4_0; }
		
		//succAnswer=Answer
		public Assignment getSuccAnswerAssignment_4_1() { return cSuccAnswerAssignment_4_1; }
		
		//Answer
		public RuleCall getSuccAnswerAnswerParserRuleCall_4_1_0() { return cSuccAnswerAnswerParserRuleCall_4_1_0; }
		
		//'struct'
		public Keyword getStructKeyword_5() { return cStructKeyword_5; }
		
		//struct=Struct
		public Assignment getStructAssignment_6() { return cStructAssignment_6; }
		
		//Struct
		public RuleCall getStructStructParserRuleCall_6_0() { return cStructStructParserRuleCall_6_0; }
		
		//('fieldset' '{' fieldset+=FieldSet ( "," fieldset+=FieldSet)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'fieldset'
		public Keyword getFieldsetKeyword_7_0() { return cFieldsetKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//fieldset+=FieldSet
		public Assignment getFieldsetAssignment_7_2() { return cFieldsetAssignment_7_2; }
		
		//FieldSet
		public RuleCall getFieldsetFieldSetParserRuleCall_7_2_0() { return cFieldsetFieldSetParserRuleCall_7_2_0; }
		
		//( "," fieldset+=FieldSet)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//fieldset+=FieldSet
		public Assignment getFieldsetAssignment_7_3_1() { return cFieldsetAssignment_7_3_1; }
		
		//FieldSet
		public RuleCall getFieldsetFieldSetParserRuleCall_7_3_1_0() { return cFieldsetFieldSetParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class OpReadElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.OpRead");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpReadKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cFieldsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cFieldsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cFieldsEStringParserRuleCall_2_1_0 = (RuleCall)cFieldsAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIdKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cIdAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_3_1_0 = (RuleCall)cIdAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFailedAnswerKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cFailedAnswerAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cFailedAnswerAnswerParserRuleCall_4_1_0 = (RuleCall)cFailedAnswerAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cSuccAnswerKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSuccAnswerAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cSuccAnswerAnswerParserRuleCall_5_1_0 = (RuleCall)cSuccAnswerAssignment_5_1.eContents().get(0);
		private final Keyword cStructKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cStructAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cStructStructParserRuleCall_7_0 = (RuleCall)cStructAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//OpRead returns OpRead:
		//    'OpRead'
		//    '{'
		//        ('fields' fields=EString)?
		//        ('id' id=EString)?
		//        ('failedAnswer' failedAnswer=Answer)?
		//        ('succAnswer' succAnswer=Answer)?
		//        'struct' struct=Struct
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'OpRead'
		//'{'
		//    ('fields' fields=EString)?
		//    ('id' id=EString)?
		//    ('failedAnswer' failedAnswer=Answer)?
		//    ('succAnswer' succAnswer=Answer)?
		//    'struct' struct=Struct
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'OpRead'
		public Keyword getOpReadKeyword_0() { return cOpReadKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('fields' fields=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'fields'
		public Keyword getFieldsKeyword_2_0() { return cFieldsKeyword_2_0; }
		
		//fields=EString
		public Assignment getFieldsAssignment_2_1() { return cFieldsAssignment_2_1; }
		
		//EString
		public RuleCall getFieldsEStringParserRuleCall_2_1_0() { return cFieldsEStringParserRuleCall_2_1_0; }
		
		//('id' id=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'id'
		public Keyword getIdKeyword_3_0() { return cIdKeyword_3_0; }
		
		//id=EString
		public Assignment getIdAssignment_3_1() { return cIdAssignment_3_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_3_1_0() { return cIdEStringParserRuleCall_3_1_0; }
		
		//('failedAnswer' failedAnswer=Answer)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'failedAnswer'
		public Keyword getFailedAnswerKeyword_4_0() { return cFailedAnswerKeyword_4_0; }
		
		//failedAnswer=Answer
		public Assignment getFailedAnswerAssignment_4_1() { return cFailedAnswerAssignment_4_1; }
		
		//Answer
		public RuleCall getFailedAnswerAnswerParserRuleCall_4_1_0() { return cFailedAnswerAnswerParserRuleCall_4_1_0; }
		
		//('succAnswer' succAnswer=Answer)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'succAnswer'
		public Keyword getSuccAnswerKeyword_5_0() { return cSuccAnswerKeyword_5_0; }
		
		//succAnswer=Answer
		public Assignment getSuccAnswerAssignment_5_1() { return cSuccAnswerAssignment_5_1; }
		
		//Answer
		public RuleCall getSuccAnswerAnswerParserRuleCall_5_1_0() { return cSuccAnswerAnswerParserRuleCall_5_1_0; }
		
		//'struct'
		public Keyword getStructKeyword_6() { return cStructKeyword_6; }
		
		//struct=Struct
		public Assignment getStructAssignment_7() { return cStructAssignment_7; }
		
		//Struct
		public RuleCall getStructStructParserRuleCall_7_0() { return cStructStructParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class OpUpdateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.OpUpdate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpUpdateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_2_1_0 = (RuleCall)cIdAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFailedAnswerKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFailedAnswerAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cFailedAnswerAnswerParserRuleCall_3_1_0 = (RuleCall)cFailedAnswerAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSuccAnswerKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSuccAnswerAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cSuccAnswerAnswerParserRuleCall_4_1_0 = (RuleCall)cSuccAnswerAssignment_4_1.eContents().get(0);
		private final Keyword cStructKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStructAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStructStructParserRuleCall_6_0 = (RuleCall)cStructAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cFieldsetKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cFieldsetAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cFieldsetFieldSetParserRuleCall_7_2_0 = (RuleCall)cFieldsetAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cFieldsetAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cFieldsetFieldSetParserRuleCall_7_3_1_0 = (RuleCall)cFieldsetAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//OpUpdate returns OpUpdate:
		//    'OpUpdate'
		//    '{'
		//        ('id' id=EString)?
		//        ('failedAnswer' failedAnswer=Answer)?
		//        ('succAnswer' succAnswer=Answer)?
		//        'struct' struct=Struct
		//        ('fieldset' '{' fieldset+=FieldSet ( "," fieldset+=FieldSet)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'OpUpdate'
		//'{'
		//    ('id' id=EString)?
		//    ('failedAnswer' failedAnswer=Answer)?
		//    ('succAnswer' succAnswer=Answer)?
		//    'struct' struct=Struct
		//    ('fieldset' '{' fieldset+=FieldSet ( "," fieldset+=FieldSet)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'OpUpdate'
		public Keyword getOpUpdateKeyword_0() { return cOpUpdateKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('id' id=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'id'
		public Keyword getIdKeyword_2_0() { return cIdKeyword_2_0; }
		
		//id=EString
		public Assignment getIdAssignment_2_1() { return cIdAssignment_2_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_1_0() { return cIdEStringParserRuleCall_2_1_0; }
		
		//('failedAnswer' failedAnswer=Answer)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'failedAnswer'
		public Keyword getFailedAnswerKeyword_3_0() { return cFailedAnswerKeyword_3_0; }
		
		//failedAnswer=Answer
		public Assignment getFailedAnswerAssignment_3_1() { return cFailedAnswerAssignment_3_1; }
		
		//Answer
		public RuleCall getFailedAnswerAnswerParserRuleCall_3_1_0() { return cFailedAnswerAnswerParserRuleCall_3_1_0; }
		
		//('succAnswer' succAnswer=Answer)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'succAnswer'
		public Keyword getSuccAnswerKeyword_4_0() { return cSuccAnswerKeyword_4_0; }
		
		//succAnswer=Answer
		public Assignment getSuccAnswerAssignment_4_1() { return cSuccAnswerAssignment_4_1; }
		
		//Answer
		public RuleCall getSuccAnswerAnswerParserRuleCall_4_1_0() { return cSuccAnswerAnswerParserRuleCall_4_1_0; }
		
		//'struct'
		public Keyword getStructKeyword_5() { return cStructKeyword_5; }
		
		//struct=Struct
		public Assignment getStructAssignment_6() { return cStructAssignment_6; }
		
		//Struct
		public RuleCall getStructStructParserRuleCall_6_0() { return cStructStructParserRuleCall_6_0; }
		
		//('fieldset' '{' fieldset+=FieldSet ( "," fieldset+=FieldSet)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'fieldset'
		public Keyword getFieldsetKeyword_7_0() { return cFieldsetKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//fieldset+=FieldSet
		public Assignment getFieldsetAssignment_7_2() { return cFieldsetAssignment_7_2; }
		
		//FieldSet
		public RuleCall getFieldsetFieldSetParserRuleCall_7_2_0() { return cFieldsetFieldSetParserRuleCall_7_2_0; }
		
		//( "," fieldset+=FieldSet)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//fieldset+=FieldSet
		public Assignment getFieldsetAssignment_7_3_1() { return cFieldsetAssignment_7_3_1; }
		
		//FieldSet
		public RuleCall getFieldsetFieldSetParserRuleCall_7_3_1_0() { return cFieldsetFieldSetParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class OpDeleteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.OpDelete");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpDeleteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_2_1_0 = (RuleCall)cIdAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFailedAnswerKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFailedAnswerAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cFailedAnswerAnswerParserRuleCall_3_1_0 = (RuleCall)cFailedAnswerAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSuccAnswerKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSuccAnswerAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cSuccAnswerAnswerParserRuleCall_4_1_0 = (RuleCall)cSuccAnswerAssignment_4_1.eContents().get(0);
		private final Keyword cStructKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStructAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStructStructParserRuleCall_6_0 = (RuleCall)cStructAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//OpDelete returns OpDelete:
		//    'OpDelete'
		//    '{'
		//        ('id' id=EString)?
		//        ('failedAnswer' failedAnswer=Answer)?
		//        ('succAnswer' succAnswer=Answer)?
		//        'struct' struct=Struct
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'OpDelete'
		//'{'
		//    ('id' id=EString)?
		//    ('failedAnswer' failedAnswer=Answer)?
		//    ('succAnswer' succAnswer=Answer)?
		//    'struct' struct=Struct
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'OpDelete'
		public Keyword getOpDeleteKeyword_0() { return cOpDeleteKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('id' id=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'id'
		public Keyword getIdKeyword_2_0() { return cIdKeyword_2_0; }
		
		//id=EString
		public Assignment getIdAssignment_2_1() { return cIdAssignment_2_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_1_0() { return cIdEStringParserRuleCall_2_1_0; }
		
		//('failedAnswer' failedAnswer=Answer)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'failedAnswer'
		public Keyword getFailedAnswerKeyword_3_0() { return cFailedAnswerKeyword_3_0; }
		
		//failedAnswer=Answer
		public Assignment getFailedAnswerAssignment_3_1() { return cFailedAnswerAssignment_3_1; }
		
		//Answer
		public RuleCall getFailedAnswerAnswerParserRuleCall_3_1_0() { return cFailedAnswerAnswerParserRuleCall_3_1_0; }
		
		//('succAnswer' succAnswer=Answer)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'succAnswer'
		public Keyword getSuccAnswerKeyword_4_0() { return cSuccAnswerKeyword_4_0; }
		
		//succAnswer=Answer
		public Assignment getSuccAnswerAssignment_4_1() { return cSuccAnswerAssignment_4_1; }
		
		//Answer
		public RuleCall getSuccAnswerAnswerParserRuleCall_4_1_0() { return cSuccAnswerAnswerParserRuleCall_4_1_0; }
		
		//'struct'
		public Keyword getStructKeyword_5() { return cStructKeyword_5; }
		
		//struct=Struct
		public Assignment getStructAssignment_6() { return cStructAssignment_6; }
		
		//Struct
		public RuleCall getStructStructParserRuleCall_6_0() { return cStructStructParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class FieldSetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.FieldSet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFieldSetAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFieldSetKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cExprKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cExprAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cExprEStringParserRuleCall_4_1_0 = (RuleCall)cExprAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//FieldSet returns FieldSet:
		//    {FieldSet}
		//    'FieldSet'
		//    name=EString
		//    '{'
		//        ('expr' expr=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{FieldSet}
		//'FieldSet'
		//name=EString
		//'{'
		//    ('expr' expr=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{FieldSet}
		public Action getFieldSetAction_0() { return cFieldSetAction_0; }
		
		//'FieldSet'
		public Keyword getFieldSetKeyword_1() { return cFieldSetKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('expr' expr=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'expr'
		public Keyword getExprKeyword_4_0() { return cExprKeyword_4_0; }
		
		//expr=EString
		public Assignment getExprAssignment_4_1() { return cExprAssignment_4_1; }
		
		//EString
		public RuleCall getExprEStringParserRuleCall_4_1_0() { return cExprEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	private final RestSystemElements pRestSystem;
	private final RequestElements pRequest;
	private final DataElements pData;
	private final OperationElements pOperation;
	private final RouteElements pRoute;
	private final ReGetElements pReGet;
	private final RePostElements pRePost;
	private final RePutElements pRePut;
	private final ReDeleteElements pReDelete;
	private final SegmentElements pSegment;
	private final EStringElements pEString;
	private final ParameterElements pParameter;
	private final AttachmentsElements pAttachments;
	private final RandomElements pRandom;
	private final AnswerElements pAnswer;
	private final StructElements pStruct;
	private final OpCreateElements pOpCreate;
	private final OpReadElements pOpRead;
	private final OpUpdateElements pOpUpdate;
	private final OpDeleteElements pOpDelete;
	private final EIntElements pEInt;
	private final FieldSetElements pFieldSet;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RestGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRestSystem = new RestSystemElements();
		this.pRequest = new RequestElements();
		this.pData = new DataElements();
		this.pOperation = new OperationElements();
		this.pRoute = new RouteElements();
		this.pReGet = new ReGetElements();
		this.pRePost = new RePostElements();
		this.pRePut = new RePutElements();
		this.pReDelete = new ReDeleteElements();
		this.pSegment = new SegmentElements();
		this.pEString = new EStringElements();
		this.pParameter = new ParameterElements();
		this.pAttachments = new AttachmentsElements();
		this.pRandom = new RandomElements();
		this.pAnswer = new AnswerElements();
		this.pStruct = new StructElements();
		this.pOpCreate = new OpCreateElements();
		this.pOpRead = new OpReadElements();
		this.pOpUpdate = new OpUpdateElements();
		this.pOpDelete = new OpDeleteElements();
		this.pEInt = new EIntElements();
		this.pFieldSet = new FieldSetElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("rest.Rest".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RestSystem returns RestSystem:
	//    {RestSystem}
	//    'RestSystem'
	//    '{'
	//        ('request' '{' request+=Request ( "," request+=Request)* '}' )?
	//    '}';
	public RestSystemElements getRestSystemAccess() {
		return pRestSystem;
	}
	
	public ParserRule getRestSystemRule() {
		return getRestSystemAccess().getRule();
	}
	
	//Request returns Request:
	//    ReGet | RePost | RePut | ReDelete;
	public RequestElements getRequestAccess() {
		return pRequest;
	}
	
	public ParserRule getRequestRule() {
		return getRequestAccess().getRule();
	}
	
	//Data returns Data:
	//    Parameter | Attachments | Random;
	public DataElements getDataAccess() {
		return pData;
	}
	
	public ParserRule getDataRule() {
		return getDataAccess().getRule();
	}
	
	//Operation returns Operation:
	//    OpCreate | OpRead | OpUpdate | OpDelete;
	public OperationElements getOperationAccess() {
		return pOperation;
	}
	
	public ParserRule getOperationRule() {
		return getOperationAccess().getRule();
	}
	
	//Route returns Route:
	//    'Route'
	//    '{'
	//        'segment' '{' segment+=Segment ( "," segment+=Segment)* '}'
	//    '}';
	public RouteElements getRouteAccess() {
		return pRoute;
	}
	
	public ParserRule getRouteRule() {
		return getRouteAccess().getRule();
	}
	
	//ReGet returns ReGet:
	//    'ReGet'
	//    '{'
	//        'route' route=Route
	//        ('data' '{' data+=Data ( "," data+=Data)* '}' )?
	//        ('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
	//    '}';
	public ReGetElements getReGetAccess() {
		return pReGet;
	}
	
	public ParserRule getReGetRule() {
		return getReGetAccess().getRule();
	}
	
	//RePost returns RePost:
	//    'RePost'
	//    '{'
	//        'route' route=Route
	//        ('data' '{' data+=Data ( "," data+=Data)* '}' )?
	//        ('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
	//    '}';
	public RePostElements getRePostAccess() {
		return pRePost;
	}
	
	public ParserRule getRePostRule() {
		return getRePostAccess().getRule();
	}
	
	//RePut returns RePut:
	//    'RePut'
	//    '{'
	//        'route' route=Route
	//        ('data' '{' data+=Data ( "," data+=Data)* '}' )?
	//        ('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
	//    '}';
	public RePutElements getRePutAccess() {
		return pRePut;
	}
	
	public ParserRule getRePutRule() {
		return getRePutAccess().getRule();
	}
	
	//ReDelete returns ReDelete:
	//    'ReDelete'
	//    '{'
	//        'route' route=Route
	//        ('data' '{' data+=Data ( "," data+=Data)* '}' )?
	//        ('ops' '{' ops+=Operation ( "," ops+=Operation)* '}' )?
	//    '}';
	public ReDeleteElements getReDeleteAccess() {
		return pReDelete;
	}
	
	public ParserRule getReDeleteRule() {
		return getReDeleteAccess().getRule();
	}
	
	//Segment returns Segment:
	//    {Segment}
	//    'Segment'
	//    '{'
	//        ('value' value=EString)?
	//    '}';
	public SegmentElements getSegmentAccess() {
		return pSegment;
	}
	
	public ParserRule getSegmentRule() {
		return getSegmentAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Parameter returns Parameter:
	//    {Parameter}
	//    'Parameter'
	//    name=EString;
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//Attachments returns Attachments:
	//    {Attachments}
	//    'Attachments'
	//    name=EString;
	public AttachmentsElements getAttachmentsAccess() {
		return pAttachments;
	}
	
	public ParserRule getAttachmentsRule() {
		return getAttachmentsAccess().getRule();
	}
	
	//Random returns Random:
	//    {Random}
	//    'Random'
	//    name=EString;
	public RandomElements getRandomAccess() {
		return pRandom;
	}
	
	public ParserRule getRandomRule() {
		return getRandomAccess().getRule();
	}
	
	//Answer returns Answer:
	//    {Answer}
	//    'Answer'
	//    '{'
	//        ('status' status=EInt)?
	//        ('return' return=EString)?
	//    '}';
	public AnswerElements getAnswerAccess() {
		return pAnswer;
	}
	
	public ParserRule getAnswerRule() {
		return getAnswerAccess().getRule();
	}
	
	//Struct returns Struct:
	//    {Struct}
	//    'Struct'
	//    '{'
	//        ('fields' fields=EString)?
	//    '}';
	public StructElements getStructAccess() {
		return pStruct;
	}
	
	public ParserRule getStructRule() {
		return getStructAccess().getRule();
	}
	
	//OpCreate returns OpCreate:
	//    'OpCreate'
	//    '{'
	//        ('id' id=EString)?
	//        ('failedAnswer' failedAnswer=Answer)?
	//        ('succAnswer' succAnswer=Answer)?
	//        'struct' struct=Struct
	//        ('fieldset' '{' fieldset+=FieldSet ( "," fieldset+=FieldSet)* '}' )?
	//    '}';
	public OpCreateElements getOpCreateAccess() {
		return pOpCreate;
	}
	
	public ParserRule getOpCreateRule() {
		return getOpCreateAccess().getRule();
	}
	
	//OpRead returns OpRead:
	//    'OpRead'
	//    '{'
	//        ('fields' fields=EString)?
	//        ('id' id=EString)?
	//        ('failedAnswer' failedAnswer=Answer)?
	//        ('succAnswer' succAnswer=Answer)?
	//        'struct' struct=Struct
	//    '}';
	public OpReadElements getOpReadAccess() {
		return pOpRead;
	}
	
	public ParserRule getOpReadRule() {
		return getOpReadAccess().getRule();
	}
	
	//OpUpdate returns OpUpdate:
	//    'OpUpdate'
	//    '{'
	//        ('id' id=EString)?
	//        ('failedAnswer' failedAnswer=Answer)?
	//        ('succAnswer' succAnswer=Answer)?
	//        'struct' struct=Struct
	//        ('fieldset' '{' fieldset+=FieldSet ( "," fieldset+=FieldSet)* '}' )?
	//    '}';
	public OpUpdateElements getOpUpdateAccess() {
		return pOpUpdate;
	}
	
	public ParserRule getOpUpdateRule() {
		return getOpUpdateAccess().getRule();
	}
	
	//OpDelete returns OpDelete:
	//    'OpDelete'
	//    '{'
	//        ('id' id=EString)?
	//        ('failedAnswer' failedAnswer=Answer)?
	//        ('succAnswer' succAnswer=Answer)?
	//        'struct' struct=Struct
	//    '}';
	public OpDeleteElements getOpDeleteAccess() {
		return pOpDelete;
	}
	
	public ParserRule getOpDeleteRule() {
		return getOpDeleteAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//FieldSet returns FieldSet:
	//    {FieldSet}
	//    'FieldSet'
	//    name=EString
	//    '{'
	//        ('expr' expr=EString)?
	//    '}';
	public FieldSetElements getFieldSetAccess() {
		return pFieldSet;
	}
	
	public ParserRule getFieldSetRule() {
		return getFieldSetAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
