/*
 * generated by Xtext 2.25.0
 */
package rest.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RestGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class RestSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.RestSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRestSystemAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRestSystemKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRequestsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cRequestsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cRequestsRequestParserRuleCall_3_2_0 = (RuleCall)cRequestsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cRequestsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cRequestsRequestParserRuleCall_3_3_1_0 = (RuleCall)cRequestsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStructsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cStructsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cStructsStructParserRuleCall_4_2_0 = (RuleCall)cStructsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cStructsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cStructsStructParserRuleCall_4_3_1_0 = (RuleCall)cStructsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAnswersKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cAnswersAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cAnswersAnswerParserRuleCall_5_2_0 = (RuleCall)cAnswersAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cAnswersAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cAnswersAnswerParserRuleCall_5_3_1_0 = (RuleCall)cAnswersAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//RestSystem returns RestSystem:
		//    {RestSystem}
		//    'RestSystem'
		//    '{'
		//        ('requests' '{' requests+=Request ( "," requests+=Request)* '}' )?
		//        ('structs' '{' structs+=Struct ( "," structs+=Struct)* '}' )?
		//        ('answers' '{' answers+=Answer ( "," answers+=Answer)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RestSystem}
		//'RestSystem'
		//'{'
		//    ('requests' '{' requests+=Request ( "," requests+=Request)* '}' )?
		//    ('structs' '{' structs+=Struct ( "," structs+=Struct)* '}' )?
		//    ('answers' '{' answers+=Answer ( "," answers+=Answer)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{RestSystem}
		public Action getRestSystemAction_0() { return cRestSystemAction_0; }
		
		//'RestSystem'
		public Keyword getRestSystemKeyword_1() { return cRestSystemKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('requests' '{' requests+=Request ( "," requests+=Request)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'requests'
		public Keyword getRequestsKeyword_3_0() { return cRequestsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//requests+=Request
		public Assignment getRequestsAssignment_3_2() { return cRequestsAssignment_3_2; }
		
		//Request
		public RuleCall getRequestsRequestParserRuleCall_3_2_0() { return cRequestsRequestParserRuleCall_3_2_0; }
		
		//( "," requests+=Request)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//requests+=Request
		public Assignment getRequestsAssignment_3_3_1() { return cRequestsAssignment_3_3_1; }
		
		//Request
		public RuleCall getRequestsRequestParserRuleCall_3_3_1_0() { return cRequestsRequestParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('structs' '{' structs+=Struct ( "," structs+=Struct)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'structs'
		public Keyword getStructsKeyword_4_0() { return cStructsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//structs+=Struct
		public Assignment getStructsAssignment_4_2() { return cStructsAssignment_4_2; }
		
		//Struct
		public RuleCall getStructsStructParserRuleCall_4_2_0() { return cStructsStructParserRuleCall_4_2_0; }
		
		//( "," structs+=Struct)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//structs+=Struct
		public Assignment getStructsAssignment_4_3_1() { return cStructsAssignment_4_3_1; }
		
		//Struct
		public RuleCall getStructsStructParserRuleCall_4_3_1_0() { return cStructsStructParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('answers' '{' answers+=Answer ( "," answers+=Answer)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'answers'
		public Keyword getAnswersKeyword_5_0() { return cAnswersKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//answers+=Answer
		public Assignment getAnswersAssignment_5_2() { return cAnswersAssignment_5_2; }
		
		//Answer
		public RuleCall getAnswersAnswerParserRuleCall_5_2_0() { return cAnswersAnswerParserRuleCall_5_2_0; }
		
		//( "," answers+=Answer)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//answers+=Answer
		public Assignment getAnswersAssignment_5_3_1() { return cAnswersAssignment_5_3_1; }
		
		//Answer
		public RuleCall getAnswersAnswerParserRuleCall_5_3_1_0() { return cAnswersAnswerParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class RequestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Request");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cReGetParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRePostParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRePutParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cReDeleteParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Request returns Request:
		//    ReGet | RePost | RePut | ReDelete;
		@Override public ParserRule getRule() { return rule; }
		
		//ReGet | RePost | RePut | ReDelete
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ReGet
		public RuleCall getReGetParserRuleCall_0() { return cReGetParserRuleCall_0; }
		
		//RePost
		public RuleCall getRePostParserRuleCall_1() { return cRePostParserRuleCall_1; }
		
		//RePut
		public RuleCall getRePutParserRuleCall_2() { return cRePutParserRuleCall_2; }
		
		//ReDelete
		public RuleCall getReDeleteParserRuleCall_3() { return cReDeleteParserRuleCall_3; }
	}
	public class OperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Operation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cOpCreateParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOpReadParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cOpUpdateParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cOpDeleteParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Operation returns Operation:
		//    OpCreate | OpRead | OpUpdate | OpDelete;
		@Override public ParserRule getRule() { return rule; }
		
		//OpCreate | OpRead | OpUpdate | OpDelete
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//OpCreate
		public RuleCall getOpCreateParserRuleCall_0() { return cOpCreateParserRuleCall_0; }
		
		//OpRead
		public RuleCall getOpReadParserRuleCall_1() { return cOpReadParserRuleCall_1; }
		
		//OpUpdate
		public RuleCall getOpUpdateParserRuleCall_2() { return cOpUpdateParserRuleCall_2; }
		
		//OpDelete
		public RuleCall getOpDeleteParserRuleCall_3() { return cOpDeleteParserRuleCall_3; }
	}
	public class StructElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Struct");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStructAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStructKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFieldsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cFieldsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cFieldsFieldParserRuleCall_4_2_0 = (RuleCall)cFieldsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cFieldsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cFieldsFieldParserRuleCall_4_3_1_0 = (RuleCall)cFieldsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Struct returns Struct:
		//    {Struct}
		//    'Struct'
		//    name=EString
		//    '{'
		//        ('fields' '{' fields+=Field ( "," fields+=Field)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Struct}
		//'Struct'
		//name=EString
		//'{'
		//    ('fields' '{' fields+=Field ( "," fields+=Field)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Struct}
		public Action getStructAction_0() { return cStructAction_0; }
		
		//'Struct'
		public Keyword getStructKeyword_1() { return cStructKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('fields' '{' fields+=Field ( "," fields+=Field)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'fields'
		public Keyword getFieldsKeyword_4_0() { return cFieldsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//fields+=Field
		public Assignment getFieldsAssignment_4_2() { return cFieldsAssignment_4_2; }
		
		//Field
		public RuleCall getFieldsFieldParserRuleCall_4_2_0() { return cFieldsFieldParserRuleCall_4_2_0; }
		
		//( "," fields+=Field)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//fields+=Field
		public Assignment getFieldsAssignment_4_3_1() { return cFieldsAssignment_4_3_1; }
		
		//Field
		public RuleCall getFieldsFieldParserRuleCall_4_3_1_0() { return cFieldsFieldParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class AnswerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Answer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAnswerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cStatusKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStatusAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStatusEIntParserRuleCall_4_0 = (RuleCall)cStatusAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cReturnKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cReturnAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cReturnEStringParserRuleCall_5_1_0 = (RuleCall)cReturnAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Answer returns Answer:
		//    'Answer'
		//    name=EString
		//    '{'
		//        'status' status=EInt
		//        ('return' return=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Answer'
		//name=EString
		//'{'
		//    'status' status=EInt
		//    ('return' return=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Answer'
		public Keyword getAnswerKeyword_0() { return cAnswerKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'status'
		public Keyword getStatusKeyword_3() { return cStatusKeyword_3; }
		
		//status=EInt
		public Assignment getStatusAssignment_4() { return cStatusAssignment_4; }
		
		//EInt
		public RuleCall getStatusEIntParserRuleCall_4_0() { return cStatusEIntParserRuleCall_4_0; }
		
		//('return' return=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'return'
		public Keyword getReturnKeyword_5_0() { return cReturnKeyword_5_0; }
		
		//return=EString
		public Assignment getReturnAssignment_5_1() { return cReturnAssignment_5_1; }
		
		//EString
		public RuleCall getReturnEStringParserRuleCall_5_1_0() { return cReturnEStringParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class RouteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Route");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRouteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSegmentsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSegmentsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSegmentsSegmentParserRuleCall_4_0 = (RuleCall)cSegmentsAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSegmentsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cSegmentsSegmentParserRuleCall_5_1_0 = (RuleCall)cSegmentsAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Route returns Route:
		//    'Route'
		//    '{'
		//        'segments' '{' segments+=Segment ( "," segments+=Segment)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Route'
		//'{'
		//    'segments' '{' segments+=Segment ( "," segments+=Segment)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Route'
		public Keyword getRouteKeyword_0() { return cRouteKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'segments'
		public Keyword getSegmentsKeyword_2() { return cSegmentsKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//segments+=Segment
		public Assignment getSegmentsAssignment_4() { return cSegmentsAssignment_4; }
		
		//Segment
		public RuleCall getSegmentsSegmentParserRuleCall_4_0() { return cSegmentsSegmentParserRuleCall_4_0; }
		
		//( "," segments+=Segment)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//segments+=Segment
		public Assignment getSegmentsAssignment_5_1() { return cSegmentsAssignment_5_1; }
		
		//Segment
		public RuleCall getSegmentsSegmentParserRuleCall_5_1_0() { return cSegmentsSegmentParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParameterAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cParameterKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Parameter returns Parameter:
		//    {Parameter}
		//    'Parameter'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Parameter}
		//'Parameter'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Parameter}
		public Action getParameterAction_0() { return cParameterAction_0; }
		
		//'Parameter'
		public Keyword getParameterKeyword_1() { return cParameterKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class ReGetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.ReGet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReGetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSuccAnswerKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSuccAnswerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cSuccAnswerAnswerCrossReference_3_0 = (CrossReference)cSuccAnswerAssignment_3.eContents().get(0);
		private final RuleCall cSuccAnswerAnswerEStringParserRuleCall_3_0_1 = (RuleCall)cSuccAnswerAnswerCrossReference_3_0.eContents().get(1);
		private final Keyword cRouteKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRouteAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRouteRouteParserRuleCall_5_0 = (RuleCall)cRouteAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cOperationsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cOperationsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cOperationsOperationParserRuleCall_6_2_0 = (RuleCall)cOperationsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cOperationsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cOperationsOperationParserRuleCall_6_3_1_0 = (RuleCall)cOperationsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cParametersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cParametersAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cParametersParameterParserRuleCall_7_2_0 = (RuleCall)cParametersAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cParametersAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_7_3_1_0 = (RuleCall)cParametersAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//ReGet returns ReGet:
		//    'ReGet'
		//    '{'
		//        'succAnswer' succAnswer=[Answer|EString]
		//        'route' route=Route
		//        ('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
		//        ('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ReGet'
		//'{'
		//    'succAnswer' succAnswer=[Answer|EString]
		//    'route' route=Route
		//    ('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
		//    ('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ReGet'
		public Keyword getReGetKeyword_0() { return cReGetKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'succAnswer'
		public Keyword getSuccAnswerKeyword_2() { return cSuccAnswerKeyword_2; }
		
		//succAnswer=[Answer|EString]
		public Assignment getSuccAnswerAssignment_3() { return cSuccAnswerAssignment_3; }
		
		//[Answer|EString]
		public CrossReference getSuccAnswerAnswerCrossReference_3_0() { return cSuccAnswerAnswerCrossReference_3_0; }
		
		//EString
		public RuleCall getSuccAnswerAnswerEStringParserRuleCall_3_0_1() { return cSuccAnswerAnswerEStringParserRuleCall_3_0_1; }
		
		//'route'
		public Keyword getRouteKeyword_4() { return cRouteKeyword_4; }
		
		//route=Route
		public Assignment getRouteAssignment_5() { return cRouteAssignment_5; }
		
		//Route
		public RuleCall getRouteRouteParserRuleCall_5_0() { return cRouteRouteParserRuleCall_5_0; }
		
		//('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'operations'
		public Keyword getOperationsKeyword_6_0() { return cOperationsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//operations+=Operation
		public Assignment getOperationsAssignment_6_2() { return cOperationsAssignment_6_2; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_6_2_0() { return cOperationsOperationParserRuleCall_6_2_0; }
		
		//( "," operations+=Operation)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//operations+=Operation
		public Assignment getOperationsAssignment_6_3_1() { return cOperationsAssignment_6_3_1; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_6_3_1_0() { return cOperationsOperationParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'parameters'
		public Keyword getParametersKeyword_7_0() { return cParametersKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_2() { return cParametersAssignment_7_2; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_2_0() { return cParametersParameterParserRuleCall_7_2_0; }
		
		//( "," parameters+=Parameter)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_3_1() { return cParametersAssignment_7_3_1; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_3_1_0() { return cParametersParameterParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class RePostElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.RePost");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRePostKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSuccAnswerKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSuccAnswerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cSuccAnswerAnswerCrossReference_3_0 = (CrossReference)cSuccAnswerAssignment_3.eContents().get(0);
		private final RuleCall cSuccAnswerAnswerEStringParserRuleCall_3_0_1 = (RuleCall)cSuccAnswerAnswerCrossReference_3_0.eContents().get(1);
		private final Keyword cRouteKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRouteAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRouteRouteParserRuleCall_5_0 = (RuleCall)cRouteAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cOperationsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cOperationsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cOperationsOperationParserRuleCall_6_2_0 = (RuleCall)cOperationsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cOperationsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cOperationsOperationParserRuleCall_6_3_1_0 = (RuleCall)cOperationsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cParametersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cParametersAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cParametersParameterParserRuleCall_7_2_0 = (RuleCall)cParametersAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cParametersAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_7_3_1_0 = (RuleCall)cParametersAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//RePost returns RePost:
		//    'RePost'
		//    '{'
		//        'succAnswer' succAnswer=[Answer|EString]
		//        'route' route=Route
		//        ('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
		//        ('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'RePost'
		//'{'
		//    'succAnswer' succAnswer=[Answer|EString]
		//    'route' route=Route
		//    ('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
		//    ('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'RePost'
		public Keyword getRePostKeyword_0() { return cRePostKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'succAnswer'
		public Keyword getSuccAnswerKeyword_2() { return cSuccAnswerKeyword_2; }
		
		//succAnswer=[Answer|EString]
		public Assignment getSuccAnswerAssignment_3() { return cSuccAnswerAssignment_3; }
		
		//[Answer|EString]
		public CrossReference getSuccAnswerAnswerCrossReference_3_0() { return cSuccAnswerAnswerCrossReference_3_0; }
		
		//EString
		public RuleCall getSuccAnswerAnswerEStringParserRuleCall_3_0_1() { return cSuccAnswerAnswerEStringParserRuleCall_3_0_1; }
		
		//'route'
		public Keyword getRouteKeyword_4() { return cRouteKeyword_4; }
		
		//route=Route
		public Assignment getRouteAssignment_5() { return cRouteAssignment_5; }
		
		//Route
		public RuleCall getRouteRouteParserRuleCall_5_0() { return cRouteRouteParserRuleCall_5_0; }
		
		//('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'operations'
		public Keyword getOperationsKeyword_6_0() { return cOperationsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//operations+=Operation
		public Assignment getOperationsAssignment_6_2() { return cOperationsAssignment_6_2; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_6_2_0() { return cOperationsOperationParserRuleCall_6_2_0; }
		
		//( "," operations+=Operation)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//operations+=Operation
		public Assignment getOperationsAssignment_6_3_1() { return cOperationsAssignment_6_3_1; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_6_3_1_0() { return cOperationsOperationParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'parameters'
		public Keyword getParametersKeyword_7_0() { return cParametersKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_2() { return cParametersAssignment_7_2; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_2_0() { return cParametersParameterParserRuleCall_7_2_0; }
		
		//( "," parameters+=Parameter)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_3_1() { return cParametersAssignment_7_3_1; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_3_1_0() { return cParametersParameterParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class RePutElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.RePut");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRePutKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSuccAnswerKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSuccAnswerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cSuccAnswerAnswerCrossReference_3_0 = (CrossReference)cSuccAnswerAssignment_3.eContents().get(0);
		private final RuleCall cSuccAnswerAnswerEStringParserRuleCall_3_0_1 = (RuleCall)cSuccAnswerAnswerCrossReference_3_0.eContents().get(1);
		private final Keyword cRouteKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRouteAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRouteRouteParserRuleCall_5_0 = (RuleCall)cRouteAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cOperationsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cOperationsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cOperationsOperationParserRuleCall_6_2_0 = (RuleCall)cOperationsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cOperationsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cOperationsOperationParserRuleCall_6_3_1_0 = (RuleCall)cOperationsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cParametersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cParametersAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cParametersParameterParserRuleCall_7_2_0 = (RuleCall)cParametersAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cParametersAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_7_3_1_0 = (RuleCall)cParametersAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//RePut returns RePut:
		//    'RePut'
		//    '{'
		//        'succAnswer' succAnswer=[Answer|EString]
		//        'route' route=Route
		//        ('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
		//        ('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'RePut'
		//'{'
		//    'succAnswer' succAnswer=[Answer|EString]
		//    'route' route=Route
		//    ('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
		//    ('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'RePut'
		public Keyword getRePutKeyword_0() { return cRePutKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'succAnswer'
		public Keyword getSuccAnswerKeyword_2() { return cSuccAnswerKeyword_2; }
		
		//succAnswer=[Answer|EString]
		public Assignment getSuccAnswerAssignment_3() { return cSuccAnswerAssignment_3; }
		
		//[Answer|EString]
		public CrossReference getSuccAnswerAnswerCrossReference_3_0() { return cSuccAnswerAnswerCrossReference_3_0; }
		
		//EString
		public RuleCall getSuccAnswerAnswerEStringParserRuleCall_3_0_1() { return cSuccAnswerAnswerEStringParserRuleCall_3_0_1; }
		
		//'route'
		public Keyword getRouteKeyword_4() { return cRouteKeyword_4; }
		
		//route=Route
		public Assignment getRouteAssignment_5() { return cRouteAssignment_5; }
		
		//Route
		public RuleCall getRouteRouteParserRuleCall_5_0() { return cRouteRouteParserRuleCall_5_0; }
		
		//('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'operations'
		public Keyword getOperationsKeyword_6_0() { return cOperationsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//operations+=Operation
		public Assignment getOperationsAssignment_6_2() { return cOperationsAssignment_6_2; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_6_2_0() { return cOperationsOperationParserRuleCall_6_2_0; }
		
		//( "," operations+=Operation)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//operations+=Operation
		public Assignment getOperationsAssignment_6_3_1() { return cOperationsAssignment_6_3_1; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_6_3_1_0() { return cOperationsOperationParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'parameters'
		public Keyword getParametersKeyword_7_0() { return cParametersKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_2() { return cParametersAssignment_7_2; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_2_0() { return cParametersParameterParserRuleCall_7_2_0; }
		
		//( "," parameters+=Parameter)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_3_1() { return cParametersAssignment_7_3_1; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_3_1_0() { return cParametersParameterParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ReDeleteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.ReDelete");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReDeleteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSuccAnswerKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSuccAnswerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cSuccAnswerAnswerCrossReference_3_0 = (CrossReference)cSuccAnswerAssignment_3.eContents().get(0);
		private final RuleCall cSuccAnswerAnswerEStringParserRuleCall_3_0_1 = (RuleCall)cSuccAnswerAnswerCrossReference_3_0.eContents().get(1);
		private final Keyword cRouteKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRouteAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRouteRouteParserRuleCall_5_0 = (RuleCall)cRouteAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cOperationsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cOperationsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cOperationsOperationParserRuleCall_6_2_0 = (RuleCall)cOperationsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cOperationsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cOperationsOperationParserRuleCall_6_3_1_0 = (RuleCall)cOperationsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cParametersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cParametersAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cParametersParameterParserRuleCall_7_2_0 = (RuleCall)cParametersAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cParametersAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_7_3_1_0 = (RuleCall)cParametersAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//ReDelete returns ReDelete:
		//    'ReDelete'
		//    '{'
		//        'succAnswer' succAnswer=[Answer|EString]
		//        'route' route=Route
		//        ('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
		//        ('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ReDelete'
		//'{'
		//    'succAnswer' succAnswer=[Answer|EString]
		//    'route' route=Route
		//    ('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
		//    ('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ReDelete'
		public Keyword getReDeleteKeyword_0() { return cReDeleteKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'succAnswer'
		public Keyword getSuccAnswerKeyword_2() { return cSuccAnswerKeyword_2; }
		
		//succAnswer=[Answer|EString]
		public Assignment getSuccAnswerAssignment_3() { return cSuccAnswerAssignment_3; }
		
		//[Answer|EString]
		public CrossReference getSuccAnswerAnswerCrossReference_3_0() { return cSuccAnswerAnswerCrossReference_3_0; }
		
		//EString
		public RuleCall getSuccAnswerAnswerEStringParserRuleCall_3_0_1() { return cSuccAnswerAnswerEStringParserRuleCall_3_0_1; }
		
		//'route'
		public Keyword getRouteKeyword_4() { return cRouteKeyword_4; }
		
		//route=Route
		public Assignment getRouteAssignment_5() { return cRouteAssignment_5; }
		
		//Route
		public RuleCall getRouteRouteParserRuleCall_5_0() { return cRouteRouteParserRuleCall_5_0; }
		
		//('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'operations'
		public Keyword getOperationsKeyword_6_0() { return cOperationsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//operations+=Operation
		public Assignment getOperationsAssignment_6_2() { return cOperationsAssignment_6_2; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_6_2_0() { return cOperationsOperationParserRuleCall_6_2_0; }
		
		//( "," operations+=Operation)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//operations+=Operation
		public Assignment getOperationsAssignment_6_3_1() { return cOperationsAssignment_6_3_1; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_6_3_1_0() { return cOperationsOperationParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'parameters'
		public Keyword getParametersKeyword_7_0() { return cParametersKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_2() { return cParametersAssignment_7_2; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_2_0() { return cParametersParameterParserRuleCall_7_2_0; }
		
		//( "," parameters+=Parameter)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_3_1() { return cParametersAssignment_7_3_1; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_3_1_0() { return cParametersParameterParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class SegmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Segment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSegmentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSegmentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Segment returns Segment:
		//    {Segment}
		//    'Segment'
		//    '{'
		//        ('value' value=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Segment}
		//'Segment'
		//'{'
		//    ('value' value=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Segment}
		public Action getSegmentAction_0() { return cSegmentAction_0; }
		
		//'Segment'
		public Keyword getSegmentKeyword_1() { return cSegmentKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('value' value=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'value'
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }
		
		//value=EString
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_3_1_0() { return cValueEStringParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class OpCreateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.OpCreate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpCreateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_2_1_0 = (RuleCall)cIdAssignment_2_1.eContents().get(0);
		private final Keyword cFailedAnswerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFailedAnswerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cFailedAnswerAnswerCrossReference_4_0 = (CrossReference)cFailedAnswerAssignment_4.eContents().get(0);
		private final RuleCall cFailedAnswerAnswerEStringParserRuleCall_4_0_1 = (RuleCall)cFailedAnswerAnswerCrossReference_4_0.eContents().get(1);
		private final Keyword cStructKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStructAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cStructStructCrossReference_6_0 = (CrossReference)cStructAssignment_6.eContents().get(0);
		private final RuleCall cStructStructEStringParserRuleCall_6_0_1 = (RuleCall)cStructStructCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cFieldsetsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cFieldsetsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cFieldsetsFieldSetParserRuleCall_7_2_0 = (RuleCall)cFieldsetsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cFieldsetsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cFieldsetsFieldSetParserRuleCall_7_3_1_0 = (RuleCall)cFieldsetsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//OpCreate returns OpCreate:
		//    'OpCreate'
		//    '{'
		//        ('id' id=EString)?
		//        'failedAnswer' failedAnswer=[Answer|EString]
		//        'struct' struct=[Struct|EString]
		//        ('fieldsets' '{' fieldsets+=FieldSet ( "," fieldsets+=FieldSet)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'OpCreate'
		//'{'
		//    ('id' id=EString)?
		//    'failedAnswer' failedAnswer=[Answer|EString]
		//    'struct' struct=[Struct|EString]
		//    ('fieldsets' '{' fieldsets+=FieldSet ( "," fieldsets+=FieldSet)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'OpCreate'
		public Keyword getOpCreateKeyword_0() { return cOpCreateKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('id' id=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'id'
		public Keyword getIdKeyword_2_0() { return cIdKeyword_2_0; }
		
		//id=EString
		public Assignment getIdAssignment_2_1() { return cIdAssignment_2_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_1_0() { return cIdEStringParserRuleCall_2_1_0; }
		
		//'failedAnswer'
		public Keyword getFailedAnswerKeyword_3() { return cFailedAnswerKeyword_3; }
		
		//failedAnswer=[Answer|EString]
		public Assignment getFailedAnswerAssignment_4() { return cFailedAnswerAssignment_4; }
		
		//[Answer|EString]
		public CrossReference getFailedAnswerAnswerCrossReference_4_0() { return cFailedAnswerAnswerCrossReference_4_0; }
		
		//EString
		public RuleCall getFailedAnswerAnswerEStringParserRuleCall_4_0_1() { return cFailedAnswerAnswerEStringParserRuleCall_4_0_1; }
		
		//'struct'
		public Keyword getStructKeyword_5() { return cStructKeyword_5; }
		
		//struct=[Struct|EString]
		public Assignment getStructAssignment_6() { return cStructAssignment_6; }
		
		//[Struct|EString]
		public CrossReference getStructStructCrossReference_6_0() { return cStructStructCrossReference_6_0; }
		
		//EString
		public RuleCall getStructStructEStringParserRuleCall_6_0_1() { return cStructStructEStringParserRuleCall_6_0_1; }
		
		//('fieldsets' '{' fieldsets+=FieldSet ( "," fieldsets+=FieldSet)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'fieldsets'
		public Keyword getFieldsetsKeyword_7_0() { return cFieldsetsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//fieldsets+=FieldSet
		public Assignment getFieldsetsAssignment_7_2() { return cFieldsetsAssignment_7_2; }
		
		//FieldSet
		public RuleCall getFieldsetsFieldSetParserRuleCall_7_2_0() { return cFieldsetsFieldSetParserRuleCall_7_2_0; }
		
		//( "," fieldsets+=FieldSet)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//fieldsets+=FieldSet
		public Assignment getFieldsetsAssignment_7_3_1() { return cFieldsetsAssignment_7_3_1; }
		
		//FieldSet
		public RuleCall getFieldsetsFieldSetParserRuleCall_7_3_1_0() { return cFieldsetsFieldSetParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class OpReadElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.OpRead");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpReadKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_2_1_0 = (RuleCall)cIdAssignment_2_1.eContents().get(0);
		private final Keyword cFailedAnswerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFailedAnswerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cFailedAnswerAnswerCrossReference_4_0 = (CrossReference)cFailedAnswerAssignment_4.eContents().get(0);
		private final RuleCall cFailedAnswerAnswerEStringParserRuleCall_4_0_1 = (RuleCall)cFailedAnswerAnswerCrossReference_4_0.eContents().get(1);
		private final Keyword cStructKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStructAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cStructStructCrossReference_6_0 = (CrossReference)cStructAssignment_6.eContents().get(0);
		private final RuleCall cStructStructEStringParserRuleCall_6_0_1 = (RuleCall)cStructStructCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cFieldsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cFieldsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final CrossReference cFieldsFieldCrossReference_7_2_0 = (CrossReference)cFieldsAssignment_7_2.eContents().get(0);
		private final RuleCall cFieldsFieldEStringParserRuleCall_7_2_0_1 = (RuleCall)cFieldsFieldCrossReference_7_2_0.eContents().get(1);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cFieldsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final CrossReference cFieldsFieldCrossReference_7_3_1_0 = (CrossReference)cFieldsAssignment_7_3_1.eContents().get(0);
		private final RuleCall cFieldsFieldEStringParserRuleCall_7_3_1_0_1 = (RuleCall)cFieldsFieldCrossReference_7_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//OpRead returns OpRead:
		//    'OpRead'
		//    '{'
		//        ('id' id=EString)?
		//        'failedAnswer' failedAnswer=[Answer|EString]
		//        'struct' struct=[Struct|EString]
		//        ('fields' '(' fields+=[Field|EString] ( "," fields+=[Field|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'OpRead'
		//'{'
		//    ('id' id=EString)?
		//    'failedAnswer' failedAnswer=[Answer|EString]
		//    'struct' struct=[Struct|EString]
		//    ('fields' '(' fields+=[Field|EString] ( "," fields+=[Field|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'OpRead'
		public Keyword getOpReadKeyword_0() { return cOpReadKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('id' id=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'id'
		public Keyword getIdKeyword_2_0() { return cIdKeyword_2_0; }
		
		//id=EString
		public Assignment getIdAssignment_2_1() { return cIdAssignment_2_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_1_0() { return cIdEStringParserRuleCall_2_1_0; }
		
		//'failedAnswer'
		public Keyword getFailedAnswerKeyword_3() { return cFailedAnswerKeyword_3; }
		
		//failedAnswer=[Answer|EString]
		public Assignment getFailedAnswerAssignment_4() { return cFailedAnswerAssignment_4; }
		
		//[Answer|EString]
		public CrossReference getFailedAnswerAnswerCrossReference_4_0() { return cFailedAnswerAnswerCrossReference_4_0; }
		
		//EString
		public RuleCall getFailedAnswerAnswerEStringParserRuleCall_4_0_1() { return cFailedAnswerAnswerEStringParserRuleCall_4_0_1; }
		
		//'struct'
		public Keyword getStructKeyword_5() { return cStructKeyword_5; }
		
		//struct=[Struct|EString]
		public Assignment getStructAssignment_6() { return cStructAssignment_6; }
		
		//[Struct|EString]
		public CrossReference getStructStructCrossReference_6_0() { return cStructStructCrossReference_6_0; }
		
		//EString
		public RuleCall getStructStructEStringParserRuleCall_6_0_1() { return cStructStructEStringParserRuleCall_6_0_1; }
		
		//('fields' '(' fields+=[Field|EString] ( "," fields+=[Field|EString])* ')' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'fields'
		public Keyword getFieldsKeyword_7_0() { return cFieldsKeyword_7_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_7_1() { return cLeftParenthesisKeyword_7_1; }
		
		//fields+=[Field|EString]
		public Assignment getFieldsAssignment_7_2() { return cFieldsAssignment_7_2; }
		
		//[Field|EString]
		public CrossReference getFieldsFieldCrossReference_7_2_0() { return cFieldsFieldCrossReference_7_2_0; }
		
		//EString
		public RuleCall getFieldsFieldEStringParserRuleCall_7_2_0_1() { return cFieldsFieldEStringParserRuleCall_7_2_0_1; }
		
		//( "," fields+=[Field|EString])*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//fields+=[Field|EString]
		public Assignment getFieldsAssignment_7_3_1() { return cFieldsAssignment_7_3_1; }
		
		//[Field|EString]
		public CrossReference getFieldsFieldCrossReference_7_3_1_0() { return cFieldsFieldCrossReference_7_3_1_0; }
		
		//EString
		public RuleCall getFieldsFieldEStringParserRuleCall_7_3_1_0_1() { return cFieldsFieldEStringParserRuleCall_7_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7_4() { return cRightParenthesisKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class OpUpdateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.OpUpdate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpUpdateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_2_1_0 = (RuleCall)cIdAssignment_2_1.eContents().get(0);
		private final Keyword cFailedAnswerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFailedAnswerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cFailedAnswerAnswerCrossReference_4_0 = (CrossReference)cFailedAnswerAssignment_4.eContents().get(0);
		private final RuleCall cFailedAnswerAnswerEStringParserRuleCall_4_0_1 = (RuleCall)cFailedAnswerAnswerCrossReference_4_0.eContents().get(1);
		private final Keyword cStructKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStructAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cStructStructCrossReference_6_0 = (CrossReference)cStructAssignment_6.eContents().get(0);
		private final RuleCall cStructStructEStringParserRuleCall_6_0_1 = (RuleCall)cStructStructCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cFieldsetsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cFieldsetsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cFieldsetsFieldSetParserRuleCall_7_2_0 = (RuleCall)cFieldsetsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cFieldsetsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cFieldsetsFieldSetParserRuleCall_7_3_1_0 = (RuleCall)cFieldsetsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//OpUpdate returns OpUpdate:
		//    'OpUpdate'
		//    '{'
		//        ('id' id=EString)?
		//        'failedAnswer' failedAnswer=[Answer|EString]
		//        'struct' struct=[Struct|EString]
		//        ('fieldsets' '{' fieldsets+=FieldSet ( "," fieldsets+=FieldSet)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'OpUpdate'
		//'{'
		//    ('id' id=EString)?
		//    'failedAnswer' failedAnswer=[Answer|EString]
		//    'struct' struct=[Struct|EString]
		//    ('fieldsets' '{' fieldsets+=FieldSet ( "," fieldsets+=FieldSet)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'OpUpdate'
		public Keyword getOpUpdateKeyword_0() { return cOpUpdateKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('id' id=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'id'
		public Keyword getIdKeyword_2_0() { return cIdKeyword_2_0; }
		
		//id=EString
		public Assignment getIdAssignment_2_1() { return cIdAssignment_2_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_1_0() { return cIdEStringParserRuleCall_2_1_0; }
		
		//'failedAnswer'
		public Keyword getFailedAnswerKeyword_3() { return cFailedAnswerKeyword_3; }
		
		//failedAnswer=[Answer|EString]
		public Assignment getFailedAnswerAssignment_4() { return cFailedAnswerAssignment_4; }
		
		//[Answer|EString]
		public CrossReference getFailedAnswerAnswerCrossReference_4_0() { return cFailedAnswerAnswerCrossReference_4_0; }
		
		//EString
		public RuleCall getFailedAnswerAnswerEStringParserRuleCall_4_0_1() { return cFailedAnswerAnswerEStringParserRuleCall_4_0_1; }
		
		//'struct'
		public Keyword getStructKeyword_5() { return cStructKeyword_5; }
		
		//struct=[Struct|EString]
		public Assignment getStructAssignment_6() { return cStructAssignment_6; }
		
		//[Struct|EString]
		public CrossReference getStructStructCrossReference_6_0() { return cStructStructCrossReference_6_0; }
		
		//EString
		public RuleCall getStructStructEStringParserRuleCall_6_0_1() { return cStructStructEStringParserRuleCall_6_0_1; }
		
		//('fieldsets' '{' fieldsets+=FieldSet ( "," fieldsets+=FieldSet)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'fieldsets'
		public Keyword getFieldsetsKeyword_7_0() { return cFieldsetsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//fieldsets+=FieldSet
		public Assignment getFieldsetsAssignment_7_2() { return cFieldsetsAssignment_7_2; }
		
		//FieldSet
		public RuleCall getFieldsetsFieldSetParserRuleCall_7_2_0() { return cFieldsetsFieldSetParserRuleCall_7_2_0; }
		
		//( "," fieldsets+=FieldSet)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//fieldsets+=FieldSet
		public Assignment getFieldsetsAssignment_7_3_1() { return cFieldsetsAssignment_7_3_1; }
		
		//FieldSet
		public RuleCall getFieldsetsFieldSetParserRuleCall_7_3_1_0() { return cFieldsetsFieldSetParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class OpDeleteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.OpDelete");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpDeleteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_2_1_0 = (RuleCall)cIdAssignment_2_1.eContents().get(0);
		private final Keyword cFailedAnswerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFailedAnswerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cFailedAnswerAnswerCrossReference_4_0 = (CrossReference)cFailedAnswerAssignment_4.eContents().get(0);
		private final RuleCall cFailedAnswerAnswerEStringParserRuleCall_4_0_1 = (RuleCall)cFailedAnswerAnswerCrossReference_4_0.eContents().get(1);
		private final Keyword cStructKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStructAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cStructStructCrossReference_6_0 = (CrossReference)cStructAssignment_6.eContents().get(0);
		private final RuleCall cStructStructEStringParserRuleCall_6_0_1 = (RuleCall)cStructStructCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//OpDelete returns OpDelete:
		//    'OpDelete'
		//    '{'
		//        ('id' id=EString)?
		//        'failedAnswer' failedAnswer=[Answer|EString]
		//        'struct' struct=[Struct|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'OpDelete'
		//'{'
		//    ('id' id=EString)?
		//    'failedAnswer' failedAnswer=[Answer|EString]
		//    'struct' struct=[Struct|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'OpDelete'
		public Keyword getOpDeleteKeyword_0() { return cOpDeleteKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('id' id=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'id'
		public Keyword getIdKeyword_2_0() { return cIdKeyword_2_0; }
		
		//id=EString
		public Assignment getIdAssignment_2_1() { return cIdAssignment_2_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_1_0() { return cIdEStringParserRuleCall_2_1_0; }
		
		//'failedAnswer'
		public Keyword getFailedAnswerKeyword_3() { return cFailedAnswerKeyword_3; }
		
		//failedAnswer=[Answer|EString]
		public Assignment getFailedAnswerAssignment_4() { return cFailedAnswerAssignment_4; }
		
		//[Answer|EString]
		public CrossReference getFailedAnswerAnswerCrossReference_4_0() { return cFailedAnswerAnswerCrossReference_4_0; }
		
		//EString
		public RuleCall getFailedAnswerAnswerEStringParserRuleCall_4_0_1() { return cFailedAnswerAnswerEStringParserRuleCall_4_0_1; }
		
		//'struct'
		public Keyword getStructKeyword_5() { return cStructKeyword_5; }
		
		//struct=[Struct|EString]
		public Assignment getStructAssignment_6() { return cStructAssignment_6; }
		
		//[Struct|EString]
		public CrossReference getStructStructCrossReference_6_0() { return cStructStructCrossReference_6_0; }
		
		//EString
		public RuleCall getStructStructEStringParserRuleCall_6_0_1() { return cStructStructEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class FieldSetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.FieldSet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFieldSetAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFieldSetKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cValueKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cValueAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_4_1_0 = (RuleCall)cValueAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//FieldSet returns FieldSet:
		//    {FieldSet}
		//    'FieldSet'
		//    name=EString
		//    '{'
		//        ('value' value=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{FieldSet}
		//'FieldSet'
		//name=EString
		//'{'
		//    ('value' value=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{FieldSet}
		public Action getFieldSetAction_0() { return cFieldSetAction_0; }
		
		//'FieldSet'
		public Keyword getFieldSetKeyword_1() { return cFieldSetKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('value' value=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'value'
		public Keyword getValueKeyword_4_0() { return cValueKeyword_4_0; }
		
		//value=EString
		public Assignment getValueAssignment_4_1() { return cValueAssignment_4_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_4_1_0() { return cValueEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class FieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.Field");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFieldAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFieldKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Field returns Field:
		//    {Field}
		//    'Field'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Field}
		//'Field'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Field}
		public Action getFieldAction_0() { return cFieldAction_0; }
		
		//'Field'
		public Keyword getFieldKeyword_1() { return cFieldKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "rest.Rest.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	
	private final RestSystemElements pRestSystem;
	private final RequestElements pRequest;
	private final OperationElements pOperation;
	private final StructElements pStruct;
	private final AnswerElements pAnswer;
	private final RouteElements pRoute;
	private final ParameterElements pParameter;
	private final ReGetElements pReGet;
	private final RePostElements pRePost;
	private final RePutElements pRePut;
	private final ReDeleteElements pReDelete;
	private final SegmentElements pSegment;
	private final EStringElements pEString;
	private final OpCreateElements pOpCreate;
	private final OpReadElements pOpRead;
	private final OpUpdateElements pOpUpdate;
	private final OpDeleteElements pOpDelete;
	private final FieldSetElements pFieldSet;
	private final FieldElements pField;
	private final EIntElements pEInt;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RestGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRestSystem = new RestSystemElements();
		this.pRequest = new RequestElements();
		this.pOperation = new OperationElements();
		this.pStruct = new StructElements();
		this.pAnswer = new AnswerElements();
		this.pRoute = new RouteElements();
		this.pParameter = new ParameterElements();
		this.pReGet = new ReGetElements();
		this.pRePost = new RePostElements();
		this.pRePut = new RePutElements();
		this.pReDelete = new ReDeleteElements();
		this.pSegment = new SegmentElements();
		this.pEString = new EStringElements();
		this.pOpCreate = new OpCreateElements();
		this.pOpRead = new OpReadElements();
		this.pOpUpdate = new OpUpdateElements();
		this.pOpDelete = new OpDeleteElements();
		this.pFieldSet = new FieldSetElements();
		this.pField = new FieldElements();
		this.pEInt = new EIntElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("rest.Rest".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RestSystem returns RestSystem:
	//    {RestSystem}
	//    'RestSystem'
	//    '{'
	//        ('requests' '{' requests+=Request ( "," requests+=Request)* '}' )?
	//        ('structs' '{' structs+=Struct ( "," structs+=Struct)* '}' )?
	//        ('answers' '{' answers+=Answer ( "," answers+=Answer)* '}' )?
	//    '}';
	public RestSystemElements getRestSystemAccess() {
		return pRestSystem;
	}
	
	public ParserRule getRestSystemRule() {
		return getRestSystemAccess().getRule();
	}
	
	//Request returns Request:
	//    ReGet | RePost | RePut | ReDelete;
	public RequestElements getRequestAccess() {
		return pRequest;
	}
	
	public ParserRule getRequestRule() {
		return getRequestAccess().getRule();
	}
	
	//Operation returns Operation:
	//    OpCreate | OpRead | OpUpdate | OpDelete;
	public OperationElements getOperationAccess() {
		return pOperation;
	}
	
	public ParserRule getOperationRule() {
		return getOperationAccess().getRule();
	}
	
	//Struct returns Struct:
	//    {Struct}
	//    'Struct'
	//    name=EString
	//    '{'
	//        ('fields' '{' fields+=Field ( "," fields+=Field)* '}' )?
	//    '}';
	public StructElements getStructAccess() {
		return pStruct;
	}
	
	public ParserRule getStructRule() {
		return getStructAccess().getRule();
	}
	
	//Answer returns Answer:
	//    'Answer'
	//    name=EString
	//    '{'
	//        'status' status=EInt
	//        ('return' return=EString)?
	//    '}';
	public AnswerElements getAnswerAccess() {
		return pAnswer;
	}
	
	public ParserRule getAnswerRule() {
		return getAnswerAccess().getRule();
	}
	
	//Route returns Route:
	//    'Route'
	//    '{'
	//        'segments' '{' segments+=Segment ( "," segments+=Segment)* '}'
	//    '}';
	public RouteElements getRouteAccess() {
		return pRoute;
	}
	
	public ParserRule getRouteRule() {
		return getRouteAccess().getRule();
	}
	
	//Parameter returns Parameter:
	//    {Parameter}
	//    'Parameter'
	//    name=EString;
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//ReGet returns ReGet:
	//    'ReGet'
	//    '{'
	//        'succAnswer' succAnswer=[Answer|EString]
	//        'route' route=Route
	//        ('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
	//        ('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
	//    '}';
	public ReGetElements getReGetAccess() {
		return pReGet;
	}
	
	public ParserRule getReGetRule() {
		return getReGetAccess().getRule();
	}
	
	//RePost returns RePost:
	//    'RePost'
	//    '{'
	//        'succAnswer' succAnswer=[Answer|EString]
	//        'route' route=Route
	//        ('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
	//        ('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
	//    '}';
	public RePostElements getRePostAccess() {
		return pRePost;
	}
	
	public ParserRule getRePostRule() {
		return getRePostAccess().getRule();
	}
	
	//RePut returns RePut:
	//    'RePut'
	//    '{'
	//        'succAnswer' succAnswer=[Answer|EString]
	//        'route' route=Route
	//        ('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
	//        ('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
	//    '}';
	public RePutElements getRePutAccess() {
		return pRePut;
	}
	
	public ParserRule getRePutRule() {
		return getRePutAccess().getRule();
	}
	
	//ReDelete returns ReDelete:
	//    'ReDelete'
	//    '{'
	//        'succAnswer' succAnswer=[Answer|EString]
	//        'route' route=Route
	//        ('operations' '{' operations+=Operation ( "," operations+=Operation)* '}' )?
	//        ('parameters' '{' parameters+=Parameter ( "," parameters+=Parameter)* '}' )?
	//    '}';
	public ReDeleteElements getReDeleteAccess() {
		return pReDelete;
	}
	
	public ParserRule getReDeleteRule() {
		return getReDeleteAccess().getRule();
	}
	
	//Segment returns Segment:
	//    {Segment}
	//    'Segment'
	//    '{'
	//        ('value' value=EString)?
	//    '}';
	public SegmentElements getSegmentAccess() {
		return pSegment;
	}
	
	public ParserRule getSegmentRule() {
		return getSegmentAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//OpCreate returns OpCreate:
	//    'OpCreate'
	//    '{'
	//        ('id' id=EString)?
	//        'failedAnswer' failedAnswer=[Answer|EString]
	//        'struct' struct=[Struct|EString]
	//        ('fieldsets' '{' fieldsets+=FieldSet ( "," fieldsets+=FieldSet)* '}' )?
	//    '}';
	public OpCreateElements getOpCreateAccess() {
		return pOpCreate;
	}
	
	public ParserRule getOpCreateRule() {
		return getOpCreateAccess().getRule();
	}
	
	//OpRead returns OpRead:
	//    'OpRead'
	//    '{'
	//        ('id' id=EString)?
	//        'failedAnswer' failedAnswer=[Answer|EString]
	//        'struct' struct=[Struct|EString]
	//        ('fields' '(' fields+=[Field|EString] ( "," fields+=[Field|EString])* ')' )?
	//    '}';
	public OpReadElements getOpReadAccess() {
		return pOpRead;
	}
	
	public ParserRule getOpReadRule() {
		return getOpReadAccess().getRule();
	}
	
	//OpUpdate returns OpUpdate:
	//    'OpUpdate'
	//    '{'
	//        ('id' id=EString)?
	//        'failedAnswer' failedAnswer=[Answer|EString]
	//        'struct' struct=[Struct|EString]
	//        ('fieldsets' '{' fieldsets+=FieldSet ( "," fieldsets+=FieldSet)* '}' )?
	//    '}';
	public OpUpdateElements getOpUpdateAccess() {
		return pOpUpdate;
	}
	
	public ParserRule getOpUpdateRule() {
		return getOpUpdateAccess().getRule();
	}
	
	//OpDelete returns OpDelete:
	//    'OpDelete'
	//    '{'
	//        ('id' id=EString)?
	//        'failedAnswer' failedAnswer=[Answer|EString]
	//        'struct' struct=[Struct|EString]
	//    '}';
	public OpDeleteElements getOpDeleteAccess() {
		return pOpDelete;
	}
	
	public ParserRule getOpDeleteRule() {
		return getOpDeleteAccess().getRule();
	}
	
	//FieldSet returns FieldSet:
	//    {FieldSet}
	//    'FieldSet'
	//    name=EString
	//    '{'
	//        ('value' value=EString)?
	//    '}';
	public FieldSetElements getFieldSetAccess() {
		return pFieldSet;
	}
	
	public ParserRule getFieldSetRule() {
		return getFieldSetAccess().getRule();
	}
	
	//Field returns Field:
	//    {Field}
	//    'Field'
	//    name=EString;
	public FieldElements getFieldAccess() {
		return pField;
	}
	
	public ParserRule getFieldRule() {
		return getFieldAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
